### ISSUE TITLE
print out with C

### ISSUE THREAD

**Issue by mahuichao** [FFTW/fftw3#100]
I want to print the out after execute plan,but I don't know how to do that.  
for(;;){
     for(;;){
          printf("?????",out[][]); 
}
}
what should I use in ? position.Thanx

**Comment by stevengj** [comment]
Assuming `out[][]` is `fftw_complex`, you can do e.g. `printf("%g%+gi\n", out[][][0], out[][][1]);`

**Comment by mahuichao** [comment]
@stevengj   Thanks guy,that works.
