### ISSUE TITLE
r2c then c2r but got -nan(ind)

### ISSUE THREAD

**Issue by mahuichao** [FFTW/fftw3#101]
Hello guys,sorry to interrupt you again,but I got some problems.Here is my core code:
```c
fftw_complex *out_left;
double *in_left;
double *iout_left;

in_left = (double*)fftw_malloc(N_L * sizeof(double));
out_left = (fftw_complex*)fftw_malloc((N_L/2+1) * sizeof(fftw_complex));
iout_left = (double*)fftw_malloc(N_L  * sizeof(double));
........
p= fftw_plan_dft_r2c_1d(N_L,in_left, out_left, FFTW_ESTIMATE);
........(the result is correct)

p1 = fftw_plan_dft_c2r_1d(N_L, out_left, iout_left, FFTW_ESTIMATE);

for (int j = 0; j < N_L; j++) {
		printf("%f\n", iout_left[j]);
}
```
and I got "-nan(ind)" ,I don't know where is wrong,anyone can help me?

**Comment by stevengj** [comment]
You should always post an complete, working example if possible.  The following example works fine for me:
```c
#include <stdio.h>
#include <fftw3.h>

int main(void)
{
    fftw_plan p, p1;
    int N_L = 10;
    fftw_complex *out_left;
    double *in_left;
    double *iout_left;
    
    in_left = (double*)fftw_malloc(N_L * sizeof(double));
    out_left = (fftw_complex*)fftw_malloc((N_L/2+1) * sizeof(fftw_complex));
    iout_left = (double*)fftw_malloc(N_L  * sizeof(double));
    
    p= fftw_plan_dft_r2c_1d(N_L,in_left, out_left, FFTW_ESTIMATE);
    p1 = fftw_plan_dft_c2r_1d(N_L, out_left, iout_left, FFTW_ESTIMATE);
    
    for (int j = 0; j < N_L; ++j)
        in_left[j] = j;

    fftw_execute(p);
    fftw_execute(p1);
    
    for (int j = 0; j < N_L; j++) {
		printf("%f\n", iout_left[j]);
    }
    return 0;
}
```
The (correct) output is:
```
0.000000
10.000000
20.000000
30.000000
40.000000
50.000000
60.000000
70.000000
80.000000
90.000000
```

**Comment by mahuichao** [comment]
sorry the complete code is :
`
fftw_plan p,p1;
fftw_complex *out_left;
double *in_left;
double *iout_left;

in_left = (double*)fftw_malloc(N_L * sizeof(double));
out_left = (fftw_complex*)fftw_malloc((N_L/2+1) * sizeof(fftw_complex));
iout_left = (double*)fftw_malloc(N_L  * sizeof(double));

// this method copy every element from matrix.m[0] to in_left

cpyInt2Double(in_left, matrix.m[0],start_index,end_index);

p= fftw_plan_dft_r2c_1d(N_L,in_left, out_left, FFTW_ESTIMATE);

fftw_execute(p);

for (int j = 0; j < N_L/2+1; j++) {
			printf("NO %d   %g%+gi\n",j,out_left[j][0],out_left[j][1]);
}
(The result is correct like matlab:
NO 0   2.04968e+06+0i
NO 1   -3479.51+10883.6i
.........
)

p1 = fftw_plan_dft_c2r_1d(N_L, out_left, iout_left, FFTW_ESTIMATE);

fftw_execute(p1);

for (int j = 0; j < N_L; j++) {
		printf("%f\n", iout_left[j]);
}
`

and I got "-nan(ind)"

**Comment by mahuichao** [comment]
God,I closed the vs,then clean the project,compile,then ......... it worked,I don't know if it is the problem of VS or fftw,but still thank you @stevengj
