### ISSUE TITLE
r2c with 2d got wrong result 

### ISSUE THREAD

**Issue by mahuichao** [FFTW/fftw3#102]
Hi,guys I got confused with the method fftw_plan_dft_r2c_2d.
I have read the document,it said the  the real data is stored as a row-major array,so,assume that I have a two dimension matrix with two rows and each row have 1024 elements like following:
`
int N_L = 1024;
int N = 256;
int Snap = N_L / N;
int n_blocks = floor(matrix.length / N_L);

fftw_plan p;
for (int i = 0; i < n_blocks; i++) {
		int start_index = i*N_L;
		int end_index = (i + 1)*N_L;

		fftw_complex (*out)[513];
		double (*in)[1024];
		double (*iout)[1024];

		in = (double(*)[1024])fftw_malloc(sizeof(double)*N_L * 2);
		out = (fftw_complex(*)[512])fftw_malloc(sizeof(fftwf_complex)*(N_L/2+1)*2);
		iout = (double(*)[1024])fftw_malloc(sizeof(double)*N_L * 2);
           
               //copy each data from matrix.m to in
		cpyInt2Double(in[0], matrix.m[0], start_index, end_index);
		cpyInt2Double(in[1], matrix.m[1], start_index, end_index);

		p = fftw_plan_dft_r2c_2d(2, N_L, in, out, FFTW_ESTIMATE);

		fftw_execute(p);

		
		for (int j = 0; j < (N_L/2+1); j++) {
			printf("NO %d  %g%+gi       %g%+g\n", j, out[0][j][0], out[0][j][1],out[1][j][0],out[1][j][1]);
		}

}

`
but the result is not what I want, they are different with the result which get from fftw_plan_dft_r2c_1d respectively.I don't know where is wrong.Thanks in advance.

**Comment by stevengj** [comment]
Small differences due to roundoff errors are to be expected, or are you seeing large differences?

**Comment by stevengj** [comment]
I don't understand why you are using things like `fftw_complex (*out)[513]` ... normally you should just have `fftw_complex *out`.  See e.g. http://www.fftw.org/fftw3_doc/Dynamic-Arrays-in-C.html#Dynamic-Arrays-in-C

**Comment by mahuichao** [comment]
oh  I see ,thank you .
