### ISSUE TITLE
Suggestion for an alternative "halfcomplex" format

### ISSUE THREAD

**Issue by mreineck** [FFTW/fftw3#105]
I'm sorry if this is not the right place to present such a suggestion, or if this topic has actually already been discussed somewhere else ... I couldn't find any mention of it on the net even after extensive searching.

Our group has been looking for a storage scheme to hold the result of an FFT transform with real-valued input data, with the requirements that the resulting array is also real-valued and has the same dimensions as the input.

For 1D transforms, FFTW's "halfcomplex" format is a good candidate, but unfortunately it does not generalize well to higher dimensions.

So we have come up with the following approach:

- when transforming a real-valued array f_x in position space to harmonic space: perform the FFT, but instead of the full complex result F_k just store the sum of real and imaginary parts of the result in a real-valued array (i.e. F2_k = F_k.re+F_k.im). This operation does not lose any information, because F_k can be reconstructed from F2_k using the fact that F_k has Hermitian symmetry.

- Transforming F2_k back to position space is done by simply performing a real FFT on it, resulting in the complex-valued array f2_x. The original f_x is then given by f2_x.re-f2_x.im (ignoring normalization for the moment).

As a consequence, simply storing the sum or real and imaginary parts on the harmonic side fulfills all our requirements. Admittedly it is not a direct representation of the actual Fourier coefficients, but
- the Fourier coefficients can be easily calculated from this representation if needed, and
- common operations like convolution can be done in this representation in exactly the same way they would be done with the complex Fourier coefficients, so in may situations there will be no need to compute them explicitly.

My questions are:
- has this suggestion already been made in the past (I'm quite sure it must have been, but as I said I haven't found any mention of it online)?
- if not, could this be of interest as a storage format for FFTW?

Thank you very much for any comments!

**Comment by stevengj** [comment]
What you are describing is essentially a multidimensional [discrete Hartley transform](https://en.wikipedia.org/wiki/Discrete_Hartley_transform).  This can be computed by FFTW via the r2r interface.

**Comment by mreineck** [comment]
Ouch! Thanks a lot for that info ... and sorry for the noise!

**Comment by stevengj** [comment]
No problem; good for you for coming up with it on your own!

**Comment by stevengj** [comment]
(Note that FFTW computes the separable form of the multi-dimensional DHT; to compute the non-separable form there is a post-processing transformation as described in the Wikipedia article.)

**Comment by stevengj** [comment]
I'm always curious to hear cases in which the DHT might be useful in real applications (compared to a real-input FFT with some other output format).   Do you have a specific application in mind where equal input/output dimensions are essential?

**Comment by mreineck** [comment]
The question turned up while working on a support library for information field theory calculations (code at https://gitlab.mpcdf.mpg.de/ift/NIFTy/, introduction at http://wwwmpa.mpa-garching.mpg.de/~ensslin/research/research_IFT.html).

In this context we are working a lot with implicitly defined operators, some of which can be applied efficiently on data in position space, while others require a harmonic space representation, so FFTs and spherical harmonic transforms are an essential building block. The code tries to be as flexible as possible in terms of data types (real or complex) and underlying geometries, and while it would of course be possible to have separate code paths for real and complex FFTs, a data representation which has the same data type and shape in both domains is very, very convenient.

Given the fact that our most common operation in harmonic space is the application of a power spectrum, and that this works in exactly the same way for Fourier-transformed and Hartley-transformed data, the DHT really will make life easier for us.
