### ISSUE TITLE
CMake Linking error when building bench target

### ISSUE THREAD

**Issue by shidephen** [FFTW/fftw3#111]
I've got a linking error using cmake when building target bench.
The symbol fftw_solvetab_rdft_r2cf cannot be found.
```
[100%] Linking C executable bench
libfftw3.so.3: undefined reference to 'fftw_solvtab_rdft_r2cf'
libfftw3.so.3: undefined reference to 'fftw_solvtab_rdft_r2cb'
libfftw3.so.3: undefined reference to 'fftw_solvtab_dft_standard'
libfftw3.so.3: undefined reference to 'fftw_solvtab_rdft_r2r'
```
What can i do for solving that problem ? 3qs.

**Comment by matteo-frigo** [comment]
See README.md: you cannot compile fftw directly from github without going through the code-generation process.  There is no official release of fftw that supports cmake (yet).

**Comment by matteo-frigo** [comment]
Try downloading fftw-3.3.7 from http://fftw.org and tell me if the problem persists.  The new release is expected to work.

**Comment by shidephen** [comment]
3q, I'll try it
