### ISSUE TITLE
[cmake] building with fortran

### ISSUE THREAD

**Issue by xoviat** [FFTW/fftw3#114]
Hi there. Any idea how we can include the fortran symbols in the fftw lib? Like, for example, the file locations that need to be compiled?

**Comment by xantares** [comment]
I dont think we have to compile any additional lib with a fortran compiler, from what I understand fortran can link to the c lib with the symbols correctly mangled thanks to the fftw3.f03 header file, which is installed by: https://github.com/FFTW/fftw3/pull/113

**Comment by xoviat** [comment]
I am still struggling with this. The CMakeLists that I am using is located at https://gist.github.com/xoviat/aa537d321696f7d2c764b672ff605612. 

The following are the exports. No dfftw functions are present, even though they should be:

https://github.com/FFTW/fftw3/blob/b267008613d082975b108252ed596ba0916ffa31/api/x77.h#L33

These functions are also present in the hombrew and linux libraries. Any help is appreciated.

```

Dump of file fftw3.lib

File Type: LIBRARY

     Exports

       ordinal    name

                  _fftw_alignment_of
                  _fftw_alloc_complex
                  _fftw_alloc_real
                  _fftw_assertion_failed
                  _fftw_cc
                  _fftw_cleanup
                  _fftw_codelet_optim
                  _fftw_cost
                  _fftw_destroy_plan
                  _fftw_estimate_cost
                  _fftw_execute
                  _fftw_execute_dft
                  _fftw_execute_dft_c2r
                  _fftw_execute_dft_r2c
                  _fftw_execute_r2r
                  _fftw_execute_split_dft
                  _fftw_execute_split_dft_c2r
                  _fftw_execute_split_dft_r2c
                  _fftw_export_wisdom
                  _fftw_export_wisdom_to_file
                  _fftw_export_wisdom_to_filename
                  _fftw_export_wisdom_to_string
                  _fftw_flops
                  _fftw_forget_wisdom
                  _fftw_fprint_plan
                  _fftw_free
                  _fftw_ialignment_of
                  _fftw_ifree
                  _fftw_import_system_wisdom
                  _fftw_import_wisdom
                  _fftw_import_wisdom_from_file
                  _fftw_import_wisdom_from_filename
                  _fftw_import_wisdom_from_string
                  _fftw_malloc
                  _fftw_malloc_plain
                  _fftw_mkprinter_file
                  _fftw_plan_awake
                  _fftw_plan_dft
                  _fftw_plan_dft_1d
                  _fftw_plan_dft_2d
                  _fftw_plan_dft_3d
                  _fftw_plan_dft_c2r
                  _fftw_plan_dft_c2r_1d
                  _fftw_plan_dft_c2r_2d
                  _fftw_plan_dft_c2r_3d
                  _fftw_plan_dft_r2c
                  _fftw_plan_dft_r2c_1d
                  _fftw_plan_dft_r2c_2d
                  _fftw_plan_dft_r2c_3d
                  _fftw_plan_guru64_dft
                  _fftw_plan_guru64_dft_c2r
                  _fftw_plan_guru64_dft_r2c
                  _fftw_plan_guru64_r2r
                  _fftw_plan_guru64_split_dft
                  _fftw_plan_guru64_split_dft_c2r
                  _fftw_plan_guru64_split_dft_r2c
                  _fftw_plan_guru_dft
                  _fftw_plan_guru_dft_c2r
                  _fftw_plan_guru_dft_r2c
                  _fftw_plan_guru_r2r
                  _fftw_plan_guru_split_dft
                  _fftw_plan_guru_split_dft_c2r
                  _fftw_plan_guru_split_dft_r2c
                  _fftw_plan_many_dft
                  _fftw_plan_many_dft_c2r
                  _fftw_plan_many_dft_r2c
                  _fftw_plan_many_r2r
                  _fftw_plan_r2r
                  _fftw_plan_r2r_1d
                  _fftw_plan_r2r_2d
                  _fftw_plan_r2r_3d
                  _fftw_print_plan
                  _fftw_printer_destroy
                  _fftw_set_timelimit
                  _fftw_sprint_plan
                  _fftw_the_planner
                  _fftw_version

  Summary

          BD .debug$S
          14 .idata$2
          14 .idata$3
           4 .idata$4
           4 .idata$5
           A .idata$6
```

**Comment by xoviat** [comment]
The file that I think is supposed to be exporting the functions doesn't even have any exports:

```
Microsoft (R) COFF/PE Dumper Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file f77api.c.obj

File Type: EXTENDED COFF OBJECT

COFF SYMBOL TABLE
000 010461BB ABS    notype       Static       | @comp.id
001 80000191 ABS    notype       Static       | @feat.00
002 00000000 SECT1  notype       Static       | .drectve
    Section length   43, #relocs    0, #linenums    0, checksum        0
004 00000000 SECT2  notype       Static       | .debug$S
    Section length  3D4, #relocs    0, #linenums    0, checksum        0
006 00000000 SECT3  notype       Static       | .debug$T
    Section length 20C0, #relocs    0, #linenums    0, checksum        0

String Table Size = 0x0 bytes

  Summary

         3D4 .debug$S
        20C0 .debug$T
          43 .drectve
```

**Comment by xoviat** [comment]
Command used to compile object:

`[334/1675] C:\PROGRA~2\MIB055~1\2017\BUILDT~1\VC\Tools\MSVC\1410~1.250\bin\HostX64\x86\cl.exe   -DFFTW_DLL -DHAVE_SSE2 -DLIBFFTWF33_EXPORTS -DWINDOWS_F77_MANGLING -D_OPENMP -Dfftw3_EXPORTS -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\kernel -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\api -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\dft -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\dft\scalar -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\dft\scalar\codelets -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\dft\simd -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\dft\simd\sse2 -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\rdft -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\rdft\scalar -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\rdft\simd -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\reodft -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7 -IC:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\simd-support /DWIN32 /D_WINDOWS /W3 /utf-8 /MP /MD /O2 /Oi /Gy /DNDEBUG /Z7   /openmp /bigobj /showIncludes /FoCMakeFiles\fftw3.dir\api\f77api.c.obj /FdCMakeFiles\fftw3.dir\ /FS -c C:\Users\User\vcpkg\buildtrees\fftw3\src\fftw-3.3.7\api\f77api.c`

**Comment by xoviat** [comment]
This problem was resolved.

**Comment by matteo-frigo** [comment]
How was it resolved?

**Comment by xoviat** [comment]
I was using vcpkg to install fftw, which used a custom cmake file (as when the port was added, no cmake file existed). Using the cmake file that comes with fftw resolved the problem.
