### ISSUE TITLE
Undefined reference to fftw_solvtab_<whatever>

### ISSUE THREAD

**Issue by firegurafiku** [FFTW/fftw3#116]
Hi!

I'm trying to build the library for the first time, using CMake instead of autotools. Unfortunately, whatever I do ends up with the following undefined references. See the steps to reproduce:

```text
$ git clone https://github.com/FFTW/fftw3.git && cd fftw3
$ mkdir build && cd build
$ cmake .. && make
<...>
[100%] Linking C executable bench
libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2cf'
libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2cb'
libfftw3.so.3: undefined reference to `fftw_solvtab_dft_standard'
libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2r'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/bench.dir/build.make:1006: bench] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/bench.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

There were no other error messages during the build. Is this the supposed behavior?

**Comment by iltommi** [comment]
Same here, on mac osx 10.12.6 using

- gcc-7 (Homebrew GCC 7.2.0) 7.2.0
- cmake version 3.9.5

**Comment by matteo-frigo** [comment]
Did you read README.md?

Do you have any suggestions on what we could do to avoid confusing people?

**Comment by firegurafiku** [comment]
@matteo-frigo 

Of course I did. I noted the statement about code generation but thought that the CMake configuration is supposed to run it if necessary. What I tried to achieve was to include fftw as a Git submodule into my project, but it seems things are not supposed to work this way.

> Do you have any suggestions on what we could do to avoid confusing people?

Perhaps, add something like the following into one of the READMEs:
```text
NOTE: You cannot simply 'git clone' this repository and expect CMake to
      take care of the rest. The provided CMakeLists.txt is meant to be
      usefull then used with the official tarball only.
```

**Comment by matteo-frigo** [comment]
I gave in my best shot in 2e0cfdda
