### ISSUE TITLE
Problem while testing fftw3 example on gfortran

### ISSUE THREAD

**Issue by pepitodouble** [FFTW/fftw3#118]
My aim is just to test FFTW on a one dimensional example. I've already installed everything, following the instructions. When I compile, it is working:

    gfortran fftg.f90 -L/usr/local/lib -lfftw3 -o test

But when I lauch the program, the terminal is giving the error:

    Program received signal SIGBUS: Access to an undefined portion of a memory object.

    Backtrace for this error:
    #0  0x7F064C6E6777
    #1  0x7F064C6E6D7E
    #2  0x7F064C038CAF
    #3  0x400FCD in MAIN__ at fftg.f90:?

I did not find any answer. Where the error is coming from? For more details, this is my code (taken from http://homepage.ntu.edu.tw/~wttsai/fortran) 

    program example

    implicit none
    include 'fftw3.f90'
    integer, parameter :: N=16
    integer*8 :: PLAN_FOR,PLAN_BAC
    real*8,dimension(N) :: IN,OUT,IN2
    real*8 :: xj
    integer :: j,k,mode
    real*8, parameter ::twopi=2.*acos(-1.)
    !Discrete data of function f(x)=cos(x)+0.2*sin(2x)
    do j=0,N-1
        xj=twopi*real(j)/real(N)
        IN(j)=cos(xj) +0.2*sin(2.*xj)
    end do

    write(*,*) "Original data"
    do j=1,N
       write(*,100) j,IN(j)
    end do
    100 format(i4,f12.5)

    ! Forward transform

    call dfftw_plan_r2r_1d(PLAN_FOR,N,IN,OUT,FFTW_R2HC,FFTW_ESTIMATE)
    call dfftw_execute_r2r(PLAN_FOR,IN,OUT)
    OUT=OUT/real(N,KIND=8)         

    ! Normalize
    write(*,*) "Fourier coefficient after forward FFT"

    do k=1,N
       mode=k-1
       if(k > N/2+1) mode=N-k+1
       write(*,100) mode,OUT(k)
    end do

    call dfftw_destroy_plan(PLAN_FOR)
    end program example

**Comment by matteo-frigo** [comment]
It is unfair to download a random program from a random place on the internet and expect us to debug it for you.

In any case, assigning IN(j) for j=0 is invalid in Fortran, where array indices start at 1.  There may be other bugs as well, I haven't checked.
