### ISSUE TITLE
Makefile issue ?, centos7,  dft and rfdt  c files can't find  necessary header files (ie ifft.h)

### ISSUE THREAD

**Issue by dbruther** [FFTW/fftw3#126]
Hello, I did a fresh git clone today and found myself unable to complete the  build
autoconf configure.ac > configure
mkdir build
../configure
make

CentOS Linux release 7.2.1511 (Core) 

[dbruther@localhost fftw3]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 42
Model name:            Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
Stepping:              7
CPU MHz:               1622.835
BogoMIPS:              6784.62
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-7

**Comment by dbruther** [comment]
for example, 
./../../../rdft/scalar/r2cb/r2cb_2.c:24:26: fatal error: codelet-rdft.h: No such file or directory
Yes the codelet-rdft.h does exist, 
./rdft/codelet-rdft.h, but the c-code apparently isn't getting the correct -I path

**Comment by dbruther** [comment]
mv -f .deps/hc2cbdft2_20.Tpo .deps/hc2cbdft2_20.Plo

libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../../../../rdft/scalar/r2cb -I../../.. -I ../../../.. -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns -ffast-math -MT codlist.lo -MD -MP -MF .deps/codlist.Tpo -c ../../../../rdft/scalar/r2cb/codlist.c -o codlist.o
../../../../rdft/scalar/r2cb/codlist.c:1:19: fatal error: ifftw.h: No such file or directory
 #include "ifftw.h"

**Comment by dbruther** [comment]
First time I've tried fftw, so if I'm making a rookie mistake, please let me know. Thank You

**Comment by matteo-frigo** [comment]
Did you read README.md?

**Comment by dbruther** [comment]
No, I did not read README.md.  But I read bootstrap.sh,  and the installation guide which all told me to do what I did.

**Comment by dbruther** [comment]
Conclusion: Newbie mistake
Best regards
