### ISSUE TITLE
fftw-wisdom-to-conf  seems to declare all wisdom files as invalid

### ISSUE THREAD

**Issue by dbruther** [FFTW/fftw3#127]
Hello, are there any tricks to making the utility below work
%create example wisdom file 
fftw-wisdom -n -o wisdomFile  cif1024  cib1024
fftw-wisdom-to-conf  < wisdomFile
This does not work.  fftw-wisdom-to-conf
It's hitting this error everytime
echo "fftw-wisdom-to-conf: invalid wisdom" 1>&2
		exit 1
Thanks in advance for your help

Regards

**Comment by dbruther** [comment]
I am working with the latest version 3.3.7

**Comment by matteo-frigo** [comment]
Can you post wisdomFile?

**Comment by dbruther** [comment]
You win!  I blew away my build, started from scratch with 3.3.7 and have no problems.
Sorry for the trouble. I'm a slow learner, but I try hard :)
Best Regards,
EE Dan in Texas
