### ISSUE TITLE
windows cmake

### ISSUE THREAD

**Issue by sunjunlishi** [FFTW/fftw3#134]
2>   Creating C:/bin/fftw37/Release/fftw3.lib and obj C:/bin/fftw37/Release/fftw3.exp
2>conf.c.obj : error LNK2019: unresolved _fftw_solvtab_dft_standard，symbols _fftw_dft_conf_standard 
2>conf.c.obj : error LNK2019: unresolved  _fftw_solvtab_rdft_r2cf，symbols _fftw_rdft_conf_standard 2>conf.c.obj : error LNK2019: unresolved   _fftw_solvtab_rdft_r2cb，symbols _fftw_rdft_conf_standard 
2>conf.c.obj : error LNK2019: unresolved  _fftw_solvtab_rdft_r2r，symbols _fftw_rdft_conf_standard 
2>C:\bin\fftw37\Release\fftw3.dll : fatal error LNK1120: 4 Unresolved external symbols

**Comment by KarrokDC** [comment]
While I'm not a FFTW dev, you should post way more information so the FFTW devs can reproduce it.

Like which compiler are you using, which cmake settings, compile options, etc

**Comment by sunjunlishi** [comment]
win10 vs2015-32  CMake 3.10.0-rc5

**Comment by sunjunlishi** [comment]
![1](https://user-images.githubusercontent.com/11845664/38861946-510faf62-4266-11e8-8cd7-1bb7e5d672b8.png)
i found it,how to generate the file

**Comment by sunjunlishi** [comment]
ubuntu error  too.
![1](https://user-images.githubusercontent.com/11845664/38864822-7daa907a-426e-11e8-96a4-5b20f9bb5689.png)

**Comment by sunjunlishi** [comment]
ubuntu  ./configure  make 
error

btool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I .. -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns -ffast-math -MT neon.lo -MD -MP -MF .deps/neon.Tpo -c neon.c -o neon.o
mv -f .deps/neon.Tpo .deps/neon.Plo
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -O3 -fomit-frame-pointer -mtune=native -malign-double -fstrict-aliasing -fno-schedule-insns -ffast-math   -o libsimd_support.la  taint.lo sse2.lo avx.lo avx-128-fma.lo avx2.lo avx512.lo kcvi.lo altivec.lo vsx.lo neon.lo  -lm 
libtool: link: rm -fr  .libs/libsimd_support.a .libs/libsimd_support.la
libtool: link: ar cru .libs/libsimd_support.a  taint.o sse2.o avx.o avx-128-fma.o avx2.o avx512.o kcvi.o altivec.o vsx.o neon.o
ar: `u' modifier ignored since `D' is the default (see `U')
libtool: link: ranlib .libs/libsimd_support.a
libtool: link: ( cd ".libs" && rm -f "libsimd_support.la" && ln -s "../libsimd_support.la" "libsimd_support.la" )
make[2]: Leaving directory '/home/sun/down/fftw3/simd-support'
Making all in dft
make[2]: Entering directory '/home/sun/down/fftw3/dft'
Making all in scalar
make[3]: Entering directory '/home/sun/down/fftw3/dft/scalar'
Making all in codelets
make[4]: Entering directory '/home/sun/down/fftw3/dft/scalar/codelets'
make[4]: *** No rule to make target 'n1_2.c', needed by 'all'。 停止。
make[4]: Leaving directory '/home/sun/down/fftw3/dft/scalar/codelets'
Makefile:470: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/sun/down/fftw3/dft/scalar'
Makefile:502: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/sun/down/fftw3/dft'
Makefile:708: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sun/down/fftw3'
Makefile:552: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yiyidhuang** [comment]
maybe you should call configure at first and then make.

**Comment by sunjunlishi** [comment]
There is no step-by-step compilation instruction on your main page.A few words

**Comment by sunjunlishi** [comment]
you don't tell us  how to cmake.(error)
you don't tell us  how to configure.(it error)
.sh error.

**Comment by stevengj** [comment]
See the https://github.com/FFTW/fftw3/blob/master/README.md file: don't try to build from git source (which requires special tools as explained in https://github.com/FFTW/fftw3/blob/master/README) unless you know what you are doing.

Instead, download the release tarball from www.fftw.org

**Comment by sunjunlishi** [comment]
http://www.fftw.org/download.html   fftw-3.3.7.tar.gz ./configure is  ok.i have resolve it.
i should see other  issue.

https://github.com/FFTW/fftw3  ./configure is  not ok.  soures are  different.
