### ISSUE TITLE
FFTW is not creating rfftwnd_mpi library

### ISSUE THREAD

**Issue by ny2292000** [FFTW/fftw3#147]
FFTW is not creating rfftwnd_mpi library

I couldn't find any reference to this problem.  I suspect it is a choice of switches at the compilation.  Reading the output of configure --help did not clarify.

This is not really an issue, I suppose.  Most likely is just my failure in understand the instructions. That said, I don't see any other place to ask this question.

Any help would be welcomed.

**Comment by stevengj** [comment]
`rfftwnd_mpi` is a function from [FFTW 2](http://www.fftw.org/fftw2_doc/fftw_4.html).    The [analogous function in FFTW3](http://fftw.org/doc/Multi_002ddimensional-MPI-DFTs-of-Real-Data.html) (in the `fftw3_mpi` library created by configuring with `--with-mpi`) is `fftw_mpi_plan_dft_r2c`
