### ISSUE TITLE
Random SIGSEGV

### ISSUE THREAD

**Issue by lev258** [FFTW/fftw3#162]
Hello.
I am trying to understand how FFTW works, made a simple program in Fortran for convolution of two discrete functions. No problem when compiling it with gfortran -o prob.exe prob.f95 -lfftw3 -lm, but running the .exe randomly produces "Program received signal SIGSEGV: Segmentation fault - invalid memory reference." message. When it doesn't, it finishes without error and I have the expected result in my Terminal window. I don't know whether my program has some problems or it's a bug in FFTW. Using FFTW stable from the homepage on Ubuntu 18.04. The program uses 2 vectors of the same size (101) from files and I add zero padding to the end of them.

```fortran
program prob
    integer, parameter :: n=101,m=2*n-1
    integer(KIND=8) :: plan1,plann
    real(KIND=8) :: ingauss(m),inlorentz(m),finale(m)
    complex(KIND=8) :: out1(m/2+1),out2(m/2+1),outt(m/2+1)
    open (unit=98, file='gauss.csv', status='old', action='read')
    open (unit=99, file='lorentz.csv', status='old', action='read')
    call dfftw_plan_dft_r2c_1d(plan1, m, ingauss, out1,&
        FFTW_FORWARD, FFTW_ESTIMATE)
    call dfftw_plan_dft_c2r_1d(plann, m/2+1, outt, finale,&
        FFTW_BACKWARD, FFTW_ESTIMATE)
    ingauss=0.
    inlorentz=0.
    read(98,*) ingauss(1:n)
    read(99,*) inlorentz(1:n)
    out1=0.
    out2=0.
    outt=0.
    finale=0.
    call dfftw_execute_dft_r2c(plan1, ingauss, out1)
    call dfftw_execute_dft_r2c(plan1, inlorentz, out2)
    outt=out1*out2
    call dfftw_execute_dft_c2r(plann, outt, finale)
    write(*,*) finale
    call dfftw_destroy_plan(plan1,plann)
    call dfftw_cleanup()
    close(98)
    close(99)
end program prob

Thank you for looking into it.

**Comment by lev258** [comment]
I know now that my code is not perfect, but the problem is still there. So far it seems I don't get this "random error" problem on Ubuntu 16.04, but it is there on 18.04. I am not sure whether gfortran changed something causing this or something else. I will be available to uncover it if needed.

**Comment by dfarns** [comment]
Can you determine WHERE in the code it is crashing?  Backtrace with a debugger, or just put some print statements in there.

I don't have your input files, but if I make some dummy input files with numbers in there your code completes with no segfault.   This is with gfortran-7 on a mac, so your hypothesis about the OS may be correct.   Are you linking statically or dynamically?  If dynamic linking, then be sure your LD_LIBRARY_PATH (etc) is set appropriately; you could be picking up the wrong libraries (ldd ./prob.exe before execution to check).  It could also be a bum fftw package on ubuntu's site, but that seems less likely.

If nothing else, try building the fftw library on your unbuntu18 box (dependencies are very light) and see if that works.

**Comment by lev258** [comment]
I built fftw from the tar.gz file on the fftw.org homepage.
Will try to do some debugging. My program itself compiles with gfortran so I don't think it is searching the wrong directory for libraries; only when I run the compiled file does it produce the error.
For now it seems the error is produced by the call dfftw_execute_dft_c2r. When SIGSEGV happens, I only see "error1" printed out, and no "error2". But the most strange thing is still the randomness. I run the file a couple of times and I cannot predict when it will work (give the exact result) or cause SIGSEGV.
Here is a more simple code. 
```fortran
program probconv
    integer, parameter :: n=101,m=201
    integer(KIND=8) :: plan1,plann
    real(KIND=8) :: ingauss(m),finale(m)
    complex(KIND=8) :: out1(m)
    open (unit=98, file='gauss.csv', status='old', action='read')
    call dfftw_plan_dft_r2c_1d(plan1, n, ingauss, out1,&
        FFTW_FORWARD, FFTW_ESTIMATE)
    call dfftw_plan_dft_c2r_1d(plann, n, out1, finale,&
        FFTW_BACKWARD, FFTW_ESTIMATE)
    ingauss=0.
    read(98,*) ingauss(1:n)
    out1=0.
    outt=0.
    finale=0.
    call dfftw_execute_dft_r2c(plan1, ingauss, out1)
    write(*,*) "error1"
    call dfftw_execute_dft_c2r(plann, out1, finale)
    write(*,*) "error2"
    write(*,*) finale/sqrt(n*n+0.)
    call dfftw_destroy_plan(plan1,plann)
    call dfftw_cleanup()
    close(98)
end program probconv

**Comment by dfarns** [comment]
You don't need a direction (e.g., FFTW_FORWARD) with c2r or r2c transforms.  See
http://www.fftw.org/fftw3_doc/Real_002ddata-DFTs.html

Also, read here about the physical and logical sizes of input/output arrays for the r2c and c2r transforms:
http://www.fftw.org/fftw3_doc/Real_002ddata-DFT-Array-Format.html

**Comment by lev258** [comment]
Okay, now I am sure this is related to the newer system (and newer gcc/gfortran). The random SIGSEGV never happens on Ubuntu 16.04 The question is whether it is a bug in the fortran library or a "regular" change that needs to be addressed in FFTW.

**Comment by matteo-frigo** [comment]
There are two bugs in your program, I think.  Both are caused by fortran's silliness.

First, you cannot pass FFTW_BACKWARD.  You are calling a function of five arguments with six arguments, which breaks a bunch of things.  The compiler should warn you but doesn't.

Second, FFTW_ESTIMATE is not defined.  I am not sure why the program compiles---probably FFTW_ESTIMATE is implicitly declared REAL and assumes a bogus value.  You must include "fftw3.f".

**Comment by lev258** [comment]
I already corrected FFTW_BACKWARD (FORWARD), no changes.
But the last thing seems to have done it. Maybe I was a bit negligent when reading the documentation, but I thought that -lfftw3 -lm is enough when compiling. Including fftw3.f seems to do the trick, haven't seen any errors since then. Will try it with my other example programs so please wait a few days and I will close this report.
Thank you for showing me the right path and creating this great FFT library.
