### ISSUE TITLE
Different pkgconfig filenames depending on build tool

### ISSUE THREAD

**Issue by EmmanuelP** [FFTW/fftw3#166]
Hi,

It looks like the name of the installed pc files are different if compiled using autotools, or CMake.

With autotools, `fftw3.pc`,or `fftw3f.pc` are installed, while with CMake, these files are named `fftw.pc' or `fftwf.pc`.

**Comment by matteo-frigo** [comment]
Can you tell me whether the attached patch works?

**Comment by matteo-frigo** [comment]
Does 77a2efdd work?

**Comment by EmmanuelP** [comment]
I'm not able to test. I have tried to build from git master, using CMake, but make fails near the end:
```
[100%] Building C object CMakeFiles/bench.dir/tests/fftw-bench.c.o
[100%] Linking C executable bench
/usr/bin/ld: libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2cf'
/usr/bin/ld: libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2cb'
/usr/bin/ld: libfftw3.so.3: undefined reference to `fftw_solvtab_dft_standard'
/usr/bin/ld: libfftw3.so.3: undefined reference to `fftw_solvtab_rdft_r2r'
collect2: erreur: ld a retourné le statut de sortie 1
make[2]: *** [CMakeFiles/bench.dir/build.make:610: bench] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/bench.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
But anyway, the change is small enough, I'm pretty sure https://github.com/FFTW/fftw3/commit/77a2efdded4dceef1e6045313ae06e27265807ec fixes the issue. The build failure is not related to this change.

**Comment by jegjessing** [comment]
I experience the same failure. I have checked CMakeLists and I can see that https://github.com/FFTW/fftw3/commit/77a2efdded4dceef1e6045313ae06e27265807ec 
has been applied. Still it I get the same error...
So, cant compile :-(
