### ISSUE TITLE
" error: identifier "__float128" is undefined " when using CUDA

### ISSUE THREAD

**Issue by TobiasWinchen** [FFTW/fftw3#18]
Dear FFTW authors,

We are trying to compile code that uses fftw and CUDA using 
Cuda  6.0.1 on a 64Bit Debian/Wheezy. Compiling the minimum example 

```
// file: test.cu
#include <fftw3.h>

int main() 
{
  fftwf_complex a;
  return 0;
}
```

with 

```
$nvcc test.cu -lfftw3 -I/usr/local/cuda/include 
```

results in several error lines : 

```
/usr/include/fftw3.h(371): error: identifier "__float128" is undefined
```

The issue is probably due to an incompatibility of nvcc and gcc regarding quadmath. For the intel compiler this is handled in line 359ff.  of  fftw3.h. Compiling the code and providing the intel flag manually

```
$nvcc test.cu -lfftw3 -I/usr/local/cuda/include -D__INTEL_COMPILER
```

works.

Cheers,

Marvin and Tobias

**Comment by rubenvb** [comment]
I'm affected by this with FFTW 3.3.4, GCC 4.9.2, and CUDA 6.5.19. Is the fix supposed to have landed in an already released version by now?

**Comment by matteo-frigo** [comment]
Sorry, no released version of fftw contains this fix.
