### ISSUE TITLE
Incorrect results when using float128

### ISSUE THREAD

**Issue by cosurgi** [FFTW/fftw3#188]
here's how I tried `fftwq` for float128:

source file `test_fftwq.cpp`:

```cpp
#include <complex>
#include <limits>
#include <iostream>
#include <boost/cstdfloat.hpp>
#include <boost/math/cstdfloat/cstdfloat_types.hpp>
#include <boost/multiprecision/float128.hpp>
#include <cmath>
#include <fftw3.h>

int main() {
	using Real = boost::float128_t;
	using Complex = std::complex<Real>;

	std::vector<Complex> in {{1,-1}, { 0 , 0 }, { 1  , 0.5} , { 0  , 0.5 } , {0.3Q, 1.1Q} };
	std::vector<Complex> out{{0, 0}, { 0 , 0 }, { 0  , 0  } , { 0  , 0   } , { 0  ,  0  } };
	size_t N=in.size();
	fftwq_plan p;
	p = fftwq_plan_dft_1d(N , (Real (*)[2])(in.data()) , (Real (*)[2])(out.data()) , FFTW_FORWARD, FFTW_ESTIMATE);
	fftwq_execute(p);
	fftwq_destroy_plan(p);

	int digs = std::numeric_limits<Real>::digits10;
	std::cout << "precision digits=" << digs << "\n";
	std::cout << std::setprecision(digs+1);
	for(size_t i = 0 ; i < N ; ++i) { std::cout << in [i] << "\n"; }
	std::cout << "---\n";
	for(size_t i = 0 ; i < N ; ++i) { std::cout << (out[i]/std::sqrt(Real(N))) << "\n"; }
	std::cout << "---\n";
	std::cout << std::sqrt(Real(3.Q)) << "\n";

}
```

the `makefile`:
```makefile
all:
	g++ -O1 -g test_fftwq.cpp -o test_fftwq -std=gnu++17 \
	-Wall -Werror=narrowing -lquadmath -lfftw3q -lfftw3l -lfftw3
run:
	test_fftwq
```

Program output:

```
precision digits=33
(1,-1)
(0,0)
(1,0.5)
(0,0.5)
(0.3,1.1)
---
(1.028591269649903260348219887616387,0.4919349550499537332100182071208808)
(-0.3409887676311503536846088281059338,-0.7922686679441966705904014368275257)
(0.1877170652969481257011204486123902,-0.2028156621435458504101773577043522)
(0.7660212886279950923293564419450544,-1.211185804131325864399418580221726)
(0.5947271215560935717150857186633783,-0.5217327983306750442191945010985525)
---
1.732050807568877293527446341505872
```

mathematica notebook for verification:

```
$MinPrecision = 35
$MaxPrecision = 10*$MinPrecision
$MaxExtraPrecision = 20*$MinPrecision

DecimalForm[Fourier[
  SetPrecision[
   {1 - 1 I,
    0 + 0 I,
    1 + 0.5 I,
    0 + 0.5 I,
    0.3 + 1.1 I
    }, $MinPrecision]], DefaultPrintPrecision -> $MinPrecision]

N[Sqrt[3], $MinPrecision]
```

mathematica output:

```
{1.0285912696499032553831515811218411+0.49193495504995377293056465907724873 I,
0.59472712155609360795727976766156939-0.52173279833067502722281005484233306 I,
0.76602128862799511969333249758965442-1.2111858041313258936156217585316901 I,
0.18771706529694810637079366934084586-0.20281566214354588546316839037883404 I,
-0.34098876763115039299538384698263451-0.79226866794419666303813812405566781 I}

1.7320508075688772935274463415058724
```

As you can see the incorrect results start after 18th numerical place, which suggests that fftwq somewhere along the way gets cut to long double. The different order of numbers is something I didn't investigate, but surely the ordering of results in table is explained in respective documentations. It is quite common to shift by one or rotate the numbers in the tables. It all depends on what is most efficient for respective FFT algorithms.

**Comment by stevengj** [comment]
Don't you have to write e.g. `3/10` and not `0.3` in Mathematica if you don't want it to be truncated to double precision?  Similarly for `11/10` instead of `1.1`.  See [here](https://reference.wolfram.com/language/tutorial/ArbitraryPrecisionNumbers.html).

**Comment by stevengj** [comment]
Note that FFTW has its own built-in accuracy tests against a (slow) arbitrary-precision FFT implementation, and for me it is reporting full quad-precision accuracy:
```sh
$ tests/bench -a 1024
1.65e-34 1.70e-34 1.83e-34 1.57e-34 1.70e-34 3.25e-34
```

**Comment by cosurgi** [comment]
You are right! I am sorry. I thought that mathematica is as easy to use as they advertise it ;) When I changed this in mathematica:

```
DecimalForm[Fourier[
  SetPrecision[
    {1 - 1 I,
    0 + 0 I,
    1 + 1/2 I,
    0 + 1/2 I,
    3/10 + 11/10 I
    }, $MinPrecision]], DefaultPrintPrecision -> $MinPrecision]
```

I obtain exactly the same result as in C++:

```
{1.0285912696499032603482198876163871+0.49193495504995373321001820712088077 I,
0.59472712155609357171508571866337838-0.52173279833067504421919450109855261 I,
0.76602128862799509232935644194505443-1.2111858041313258643994185802217263 I,
0.18771706529694812570112044861239016-0.20281566214354585041017735770435222 I,
-0.34098876763115035368460882810593380-0.79226866794419667059040143682752589 I}
```

We can close this issue, and I should keep in mind to never use decimal representation in mathematica.

**Comment by stevengj** [comment]
Yes, I just checked against another arbitrary-precision FFT implementation, in [this Julia package](https://github.com/JuliaApproximation/FastTransforms.jl/blob/master/src/fftBigFloat.jl), using 256-bit floating-point arithmetic (via GNU MPFR), and verified that FFTW's output is correct to quad precision.

**Comment by cosurgi** [comment]
@stevengj thank you very much for your quick response. :)

I will remember to never write decimal representation in mathematica. Usually I avoid that, but I thought that explicitly specifying `$MinPrecision` is enough to be able to write decimal floating point in mathematica.
