### ISSUE TITLE
Creating a plan without prior knowledge of data size

### ISSUE THREAD

**Issue by MDThommo81** [FFTW/fftw3#189]
Hi there,
I couldn't see this immediately in the title of any other "issues" so I apologize if I've missed it.
Essentially I want to use FFTW in my C# projects using FFTW.NET however I can't work out how to create plans without prior knowledge of the transform length/data length.  The manual indicates the importance of creating plans, but it always uses an integer "n" which specifies the size of the transform you want to compute...

I've tried using the FFT without first computing a plan and it is incredible slow to give the DFT, whereas it takes a split second when using MATLAB...  So the data can't be that big.  

I'm assuming I need to create a plan first to speed up my code, but how can I do that when I don't know the length of my data?  Any advice would be greatly received!  Thank you!!

**Comment by stevengj** [comment]
If you are doing transforms over and over, just cache the plan once you know what `n` is.

(Matlab caches plans, I believe.  It also precomputes and saves FFTW "wisdom" for common sizes, e.g. powers of 2.)
