### ISSUE TITLE
Test for -Wl,-no_compact_unwind not working

### ISSUE THREAD

**Issue by MarcusCalhoun-Lopez** [FFTW/fftw3#193]
On older macOS systems, the [test](https://github.com/FFTW/fftw3/blob/c69d6c3c7512a814efe229d15e51dda0c1590ee6/configure.ac#L391) for `-Wl,-no_compact_unwind` does not actually test anything.
Even when the linker flag `-no_compact_unwind` is unsupported, the test succeeds because no linking is done (however, there is the warning `-no_compact_unwind: linker input file unused because linking not done`).

**Comment by stevengj** [comment]
Closed by  #326
