### ISSUE TITLE
[Q] Generate RDFT code for minimal executable size

### ISSUE THREAD

**Issue by Rikorose** [FFTW/fftw3#200]
Hi,

for a personal project, I am trying to get FFTW working on a micro-controller. Dynamically linking is not an option and statically linking easily results in executable sizes > 4MB. Can you point me towards generating code for a fixed size (like 64 point) RDFT, which does not require static linking to the whole FFTW library?

If I understand the code generation section of the documentation correctly, I can generate differently sized DFTs by modifying the makefiles in e.g. rdft/scalar/r2cf. The resulting c files are getting compiled to `rdft/scalar/r2cf/librdft_scalar_r2cf.la`, which I should be able to statically link to.
I guess, I have to forward declare the functions e.g. from `rdft/scalar/r2cf/r2cf_64.c`, like this
```c
static void r2cf_64(R * R0, R * R1, R * Cr, R * Ci, stride rs, stride csr, stride csi, INT v, INT ivs, INT ovs);
```

How can I use this function? What are the different arguments?

Another hint would be nice regarding a generated r2hc transform. In rdft/scalar/r2r are only REDFT (DCT), RODFT (DST) and DHT defined. How can I add a code generation of FFTW_R2HC tranform?

<details>
  <summary>Click to expand</summary>
My initial try was:

```patch
diff --git a/genfft/gen_r2r.ml b/genfft/gen_r2r.ml
index 521eb4a1..55d2dae0 100644
--- a/genfft/gen_r2r.ml
+++ b/genfft/gen_r2r.ml
@@ -225,7 +225,7 @@ let generate n mode =
       "static const kr2r_desc desc = { %d, \"%s\", %s, &GENUS, %s };\n\n"
       n name (flops_of tree)
       (match mode with
-      | RDFT -> "RDFT00"
+      | RDFT -> "R2HC"
       | HDFT -> "HDFT00"
       | DHT  -> "DHT"
       | REDFT00 -> "REDFT00"
diff --git a/rdft/scalar/r2r/Makefile.am b/rdft/scalar/r2r/Makefile.am
index 98ca4d2e..1236032d 100644
--- a/rdft/scalar/r2r/Makefile.am
+++ b/rdft/scalar/r2r/Makefile.am
@@ -33,8 +33,10 @@ O11 = # o11_2.c o11_3.c o11_4.c o11_5.c o11_6.c o11_7.c o11_8.c
 # dht_<n> is a hard-coded DHT of size <n>
 DHT = # dht_2.c dht_3.c dht_4.c dht_5.c dht_6.c dht_7.c dht_8.c

+RHC00 = r2hc_64.c
+
 ###########################################################################
-ALL_CODELETS = $(E00) $(E01) $(E10) $(E11) $(O00) $(O01) $(O10) $(O11) $(DHT)
+ALL_CODELETS = $(E00) $(E01) $(E10) $(E11) $(O00) $(O01) $(O10) $(O11) $(DHT) $(RHC00)

 BUILT_SOURCES= $(ALL_CODELETS) $(CODLIST)

@@ -86,4 +88,8 @@ o11_%.c:  $(CODELET_DEPS) $(GEN_R2R)
 dht_%.c:  $(CODELET_DEPS) $(GEN_R2R)
 	($(PRELUDE_COMMANDS_RDFT); $(TWOVERS) $(GEN_R2R) $(FLAGS_DHT) -dht -sign 1 -n $* -name dht_$* -include "rdft/scalar/r2r.h") | $(ADD_DATE) | $(INDENT) >$@

+
+r2hc_%.c:  $(CODELET_DEPS) $(GEN_R2R)
+	($(PRELUDE_COMMANDS_RDFT); $(TWOVERS) $(GEN_R2R) $(FLAGS_DHT) -rdft -sign 1 -n $* -name dht_$* -include "rdft/scalar/r2r.h") | $(ADD_DATE) | $(INDENT) >$@
+
 endif # MAINTAINER_MODE
```
But failed with this message:
https://gist.github.com/Rikorose/32cdb9e048fbd09dc21f4a5e94869f41

</details>

**Comment by matteo-frigo** [comment]
Re: generating r2hc codelets: FFTW already generates r2hc codelets (and their inverses hc2r) in the rdft/scalar/r2cf/ directory.  These codelets are used for two purposes:

1) to compute the r2hc transform (from N reals to N "halfcomplex", where a halfcomplex array stores the N/2+1 real parts first, followed by the N-(N/2+1) imaginary parts in reverse order.

2) to compute the r2c transform, from N reals to (N/2+1) complex numbers stored as real part followed by imaginary part.  The codelet itself only stores N-(N/2+1) imaginary parts as in case 1.  External code sets one or two imaginary parts to zero as needed.  For example, the DC component (frequency 0) and the Nyquist component (frequency N/2 for even N) are purely real and they are not stored in the halfcomplex format, so the codelet does not compute them, but he complex format requires the imaginary parts to be set to zero.

1) and 2) can be computed by the same code if you are willing to play with the strides of the output.  In case 1, real elements of the output have stride 1 and imaginary elements have stride -1.  In case 2, both real and imaginary elements have stride 2.

This explanation should give you some idea of the meanings of the various parameters.  Let's focus on the r2hc codelet.  To play this game, we need separate pointers to the real and imaginary part of the complex array (Cr, Ci) as well as separate strides (csr, csi).  You may think that you would only need one pointer to the real input as well as one stride (rs) for the real input, but there is some other screw case (which I forgot) where it is convenient to have two separate pointers R0 and R1, where R0 points to the even elements and R1 points to the odd elements (for an in-place transform, we would have R0=Cr and R1=Ci, but while usually Ci=Cr+1, the code works even without this assumption, so you need to distinguish R0 and R1 if you want in-place transforms where the real and imaginary parts are stored in different places).

Finally, as usual in FFTW, the codelet computes v transforms in a loop, advancing input pointers by ivs and output pointers by ovs at each iteration.

**Comment by Rikorose** [comment]
Thanks for your reply! I will try to get a working example.

To clarify for me. So assuming case 1, with an RDFT of order N = 16, I use the following function:
```cpp
static void r2cf_16(R *R0, R *R1, R *Cr, R *Ci, stride rs, stride csr,
                    stride csi, INT v, INT ivs, INT ovs) {...}
```
I have an in/out buffer `double buf[16]`.  R0 points to the 0th element (`double *R0 = &buf[0]`), R1 to the 1st (`R1 = &buf[1])`. Now the output should be looking like
```
C=[r0,r1,r2,r3,r4,r5,r6,r7,r8,r9,i7,i6,i5,i4,i3,i2,i1]
    ^                                               ^
    Cr  -> csr = 1                    csi = -1 <-  Ci
```
So `Cr=&buf[0]` and `Ci=&buf[7]`. Since I only want a single RDFT transform for now, is `v=1`. And ivs and ovs also I guess (or it doesn't matter).

**Comment by matteo-frigo** [comment]
I forgot exactly what conventions we used, but I think you want Ci=&buf[8] (i.e., Ci should point to i0, which is not stored, and it would point to i0 in case 2).

**Comment by Rikorose** [comment]
Thanks for your help! 

If anyone is interested and finds this later, please see this gist for a working c++ version:
https://gist.github.com/Rikorose/2b73f19acc86ad4b9258f69c7d0166c4
