### ISSUE TITLE
Used MPI tag is non-conforming

### ISSUE THREAD

**Issue by jprotze** [FFTW/fftw3#206]
According to the MPI specification, the tag used in communication may not be larger than `MPI_TAG_UB`. The code should either check for this value, or not exceed the smallest possible value of `MPI_TAG_UB`, which is `2^31-1=0x7fff`

https://github.com/FFTW/fftw3/blob/master/mpi/transpose-pairwise.c#L72

Both of the `MPI_Sendrecv` calls can use a bigger tag. I suggest to bit-wise and with `0x7fff`

**Comment by stevengj** [comment]
Hmm, looks like we saw this before, but mistakenly used 0xffff rather than 0x7fff (7335ef11cd5e2e9962dbc41c42e5c14e156e6f82).

**Comment by stevengj** [comment]
(I don't think the tag is actually really necessary in this call — a tag of 0 should work as well.)
