### ISSUE TITLE
When are new versions tagged?

### ISSUE THREAD

**Issue by galenlynch** [FFTW/fftw3#210]
I was wondering when new versions of FFTW3 are tagged? I would like to use `planner_nthreads`, introduced in #205, but understand that adding a new function may not be enough to merit a new minor (or patch?) version.

**Comment by stevengj** [comment]
I'd be okay with tagging 3.3.9; there have been a few other small updates since 3.3.8  @matteo-frigo, any thoughts?

**Comment by galenlynch** [comment]
Gentle bump, would love to use `planner_nthreads`.

**Comment by calebzulawski** [comment]
I would like to bump this as well, as I have been waiting on #177 (fixing AVX-512 builds on clang).

**Comment by stevengj** [comment]
Candidate release tarball: http://fftw.org/~athena/fftw-3.3.9-rc1.tar.gz

Please bang on it to make sure there are no last-minute problems.

**Comment by calebzulawski** [comment]
`make check` passes for me (LLVM 10)! Thanks!

**Comment by stevengj** [comment]
FFTW 3.3.9 is tagged and available from http://fftw.org/download.html

**Comment by calebzulawski** [comment]
Thank you!

**Comment by galenlynch** [comment]
Thanks!

**Comment by Lqlsoftware** [comment]
Thanks!
