### ISSUE TITLE
Location of executable

### ISSUE THREAD

**Issue by atmosman** [FFTW/fftw3#215]
Hi,
  I downloaded the necessary files (I think) from the fftw website.  Am running Mac OS Catalina on an iMac.  Found I needed to remove g77 from the configure file and replace it with gfortran, since Catalina will not run 32 bit applications.  Executed the following as specified in the README:

               ./configure
               make
               make install

using sudo.    Seems to have compiled and link, because when I run the benchmark code, it returns answers that make sense.  
However, I cannot find where the executable is located. I do a which fftw and the OS returns on the command line:

               fftw: Command not found.

Help would be greatly appreciated,
Philip Dumont

**Comment by Lqlsoftware** [comment]
`fftw` is a library not executable. if you want to do some test, build your own code or go into the test dir `fftw-3.3.8/test` and `make` the bench executable.
