### ISSUE TITLE
fftw3 fall in fftw_plan_dft_r2c_1d

### ISSUE THREAD

**Issue by ValentinNikin** [FFTW/fftw3#218]
Hello! 

I use fftw3 to calculate signal spectrum.

It's my code to initialize plan:
_inSignal = new double[_windowSizeBytes];
_outSignal = new fftw_complex[_windowSizeBytes];
_plan = fftw_plan_dft_r2c_1d(_windowSizeBytes, _inSignal, _outSignal, FFTW_ESTIMATE);

And one time I catch the next error. What cause the problem? This problem reproduced only one time for me.

My fftw version: 3.3.5-3

*** Error in `./signal-spectrum': free(): invalid next size (normal): 0x00007fa844160e60 ***

======= Backtrace: =========

/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7fa87a36bbfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7fa87a371fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7fa87a37280e]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(+0x2626b)[0x7fa88669e26b]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(+0xf6c11)[0x7fa88676ec11]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_mkapiplan+0xf0)[0x7fa88676ede0]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_plan_many_dft_r2c+0x160)[0x7fa886772010]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_plan_dft_r2c+0x25)[0x7fa8867714f5]
/usr/lib/x86_64-linux-gnu/libfftw3.so.3(fftw_plan_dft_r2c_1d+0x23)[0x7fa886771413]
./signal-spectrum(_ZN24AudioTestSignalInspectorC2Eiidii+0x14a)[0x55748ae659ae]
./signal-spectrum(_ZN9__gnu_cxx13new_allocatorI24AudioTestSignalInspectorE9constructIS1_JRiS4_RdiiEEEvPT_DpOT0_+0xac)[0x55748acf85b6]
./signal-spectrum(_ZNSt16allocator_traitsISaI24AudioTestSignalInspectorEE9constructIS0_JRiS4_RdiiEEEvRS1_PT_DpOT0_+0x8d)[0x55748acf7fa5]

**Comment by ValentinNikin** [comment]
I found the cause of the problem. My application is multithreading, fftw_plan_dft_r2c_1d is not thread safe. If I use 1 thread, all ok.

**Comment by stevengj** [comment]
Yes, see the manual on thread safety.
