### ISSUE TITLE
Plans with 0 stride

### ISSUE THREAD

**Issue by marekdam** [FFTW/fftw3#219]
In my code, I often call FFTW with garbage plan parameters. For example, below I create a plan with 0 stride. I assumed that it would return a NULL plan which I check for later, but here it returns a valid plan. I can also make plans where the howmany_dims[0].os is 0 and the transform stride is 1. Similar behaviour for the advanced interface.

Is it safe to use these plans or is this a bug?

     `{
		const int rank = 1;
		fftw_iodim dims[rank];

		dims[0].n = 4;
		dims[0].is = 0;
		dims[0].os = dims[0].is;

		int howmany_rank = 1;
		fftw_iodim howmany_dims[howmany_rank];
		howmany_dims[0].n = 1;
		howmany_dims[0].os = howmany_dims[0].is = dims[0].n * dims[0].is;

		fftw_complex *in =
			fftw_alloc_complex(dims[0].n * dims[0].is * howmany_dims[0].n * howmany_dims[0].is);
		fftw_complex *out =
			fftw_alloc_complex(dims[0].n * dims[0].is * howmany_dims[0].n * howmany_dims[0].is);

		fftw_plan plan_guru = fftw_plan_guru_dft(rank, dims, howmany_rank, howmany_dims, in, out,
												 FFTW_FORWARD, FFTW_MEASURE);

		if (plan_guru)
		{
			fftw_print_plan(plan_guru);
			fftw_destroy_plan(plan_guru);
		}

		fftw_free(in);
		fftw_free(out);
	}`

**Comment by matteo-frigo** [comment]
In general we don't attempt to validate that the strides are meaningful.  For example, you can pass a 10x10 array with strides 7x1 and we don't detect that.  Basically this is C, you are responsible for setting up the pointer arithmetic correctly and for allocating enough memory for the input/output arrays.

I think these 0-stride plans are "safe" in the sense that they won't crash, but I doubt that the result will make any sense.
