### ISSUE TITLE
[ Question ] DFT matrices 

### ISSUE THREAD

**Issue by andrewshyichuk** [FFTW/fftw3#222]
Dear FFTW3 Developers, 

I have a question regarding the use of FFT. Please forgive me if this is the wrong place to ask, and for being a noob. 

I use plane-wave density functional theory codes in my research. 
They rely heavily on FFT, and call it thousands of times per run.

I wonder if DFT matrices are calculated anew on every call.
If so, would it improve the overall performance of the calling code if the matrices were calculated once and then reused?

If not, is there a different thing that is universal for any FFT of a specific size, which is calculated on every call?

Is there a practical sense in looking for this kind of optimization of a long series of the same-size FFTs?

Thank you in advance.
Best regards.
Andrew

**Comment by stevengj** [comment]
1. FFT algorithms don't calculate the DFT matrix at all.  Naively computing the DFT matrix requires Θ(n²) storage, and transforming a vector with it costs Θ(n²) time (the complexity of a generic matrix-vector multiply) for vectors of length n.   An FFT, in contrast, requires only Θ(n) storage and Θ(n log n) time.

2. The entire structure of the FFTW library is optimized precisely for the situation of performing many FFTs of the same size.   FFTW's "plan" data structure indeed encapusulates as much re-usable information as possible (algorithm choices, tables of trigonometric constants, etc.).

3. Density-functional theory (e.g. ABINIT) was one of the first users of FFTW.  Even before that, I used it for solving Bloch-periodic Maxwell equations (with the [MPB software](https://github.com/NanoComp/mpb)) for band structures of [photonic crystals](http://ab-initio.mit.edu/book/), which is somewhat similar in spirit to density functional theory but linear (bosons, not fermions).
