### ISSUE TITLE
Documentation of flag FFTW_ESTIMATE_PATIENT

### ISSUE THREAD

**Issue by dfarns** [FFTW/fftw3#223]
I see this in the source as one of the "undocumented guru" flags, but can you please provide a description?  Would this somehow guarantee a recurring plan for the same problem, as with FFTW_ESTIMATE, but choose a "better" plan and improve execute performance?  Thanks!

**Comment by stevengj** [comment]
It is just an experiment with estimated costs but applied to a larger space of plans.   It probably produces slower plans in practice — there's certainly no guarantee that it is better, since it is still limited by the fact that it is not performing any timing measurements.

**Comment by dfarns** [comment]
Thank you for the explanation.
