### ISSUE TITLE
`tests/bench` does not honor -v<N> for verbose

### ISSUE THREAD

**Issue by hominhquan** [FFTW/fftw3#250]
I see that setting `-v<N>` to `tests/bench` does not produce any verbose message, whereas it is expected to "output the created plans with fftw_print_plan" - according to https://github.com/FFTW/fftw3/blob/master/tests/README#L42-L45:

```bash
$ tests/bench -oestimate --verify of4096 -v3
```

**Comment by matteo-frigo** [comment]
Try -v3 *before* of4096.

tests/bench is old-school unix: options must come before non-option arguments.

**Comment by hominhquan** [comment]
It should be even before --verify

```
$ tests/bench -oestimate --verify -v3 of4096
bench: problem.c:96: assertion failed: isdigit(*s)
```

```
$ tests/bench -oestimate -v3 --verify of4096
# get plan info, flops count and reporting etc. 
```

Thanks for your reply. I will change my commands accordingly.
