### ISSUE TITLE
SIMD is unnormal when I compute non power of 2 size.

### ISSUE THREAD

**Issue by pidanself** [FFTW/fftw3#257]
I'm trying to port fftw to fit RISC SIMD instructions.

When I use tests/bench to test 18225 1D FFT by using one thread, it won't use simd codelets but only use scalar codelets. But simd is normal for size of 12000.

The situation puzzles me. I want to use simd codelets to compute 18225 1D FFT and look for why simd is unnormal.

How do I force tests/bench to only use simd codelets? One way which I can think of is that delete all scalar codelets, but it's too violent.

**Comment by stevengj** [comment]
Works for me with AVX2 SIMD:
```
stevenj@macbook-pro-123 fftw3 % tests/bench -v2 -o patient 18225
planner time: 4.55153 s
(dft-ct-dit/9
  (dftw-direct-9/32 "t1fuv_9_avx")
  (dft-ct-dit/9
    (dftw-direct-9/32-x9 "t1fuv_9_avx")
    (dft-vrank>=1-x9/1
      (dft-ct-dit/15
        (dftw-direct-15/28-x9 "t1fv_15_avx2_128")
        (dft-vrank>=1-x9/-1
          (dft-direct-15-x15 "n1fv_15_avx2"))))))
flops: 207818 add, 106142 mul, 57268 fma
estimated cost: 428527.415900, pcost = 323015.000000
Problem: 18225, setup: 4.55 s, time: 126.21 us, ``mflops'': 10219.001
Took 8 measurements for at least 10.00 ms each.
Time: min 126.21 us, max 151.33 us, avg 137.93 us, median 138.53 us
```

**Comment by pidanself** [comment]
> > Works for me with AVX2 SIMD:
> > ```
> > stevenj@macbook-pro-123 fftw3 % tests/bench -v2 -o patient 18225
> > planner time: 4.55153 s
> > (dft-ct-dit/9
> >   (dftw-direct-9/32 "t1fuv_9_avx")
> >   (dft-ct-dit/9
> >     (dftw-direct-9/32-x9 "t1fuv_9_avx")
> >     (dft-vrank>=1-x9/1
> >       (dft-ct-dit/15
> >         (dftw-direct-15/28-x9 "t1fv_15_avx2_128")
> >         (dft-vrank>=1-x9/-1
> >           (dft-direct-15-x15 "n1fv_15_avx2"))))))
> > flops: 207818 add, 106142 mul, 57268 fma
> > estimated cost: 428527.415900, pcost = 323015.000000
> > Problem: 18225, setup: 4.55 s, time: 126.21 us, ``mflops'': 10219.001
> > Took 8 measurements for at least 10.00 ms each.
> > Time: min 126.21 us, max 151.33 us, avg 137.93 us, median 138.53 us
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (The `t1f*v` and `n1f*v` codelets are SIMD.)
> 
> what t1fuv_* means? Its input data is unaligned? Or its stride could cause unaligned? :)

Does it mean that if we want to compute 18225 by pure simd-codelets, we must deal some data that are unaligned? If so, fftw will select pure scalar-codelets to compute 18225 in some machines that deal unaligned very slowly.

**Comment by pidanself** [comment]
> > what t1fuv_* means?
> 
> It's not unaligned, but it sometimes has lower alignment requirements than the `t1fv*` codelets.
> 
> The "u" refers to an [alternative storage scheme](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/codlist.mk#L41-L47) for the "twiddle factors" ωₖ = exp(2πink/N) used in the Cooley–Tukey steps. In particular, the [only difference](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/common/Makefile.am#L36-L40) from the t1fv codelets is that they include [`t1fu.h`](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/t1fu.h) rather than [`t1f.h`](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/t1f.h). In particular, the alignment checks for `t1fu.h` codelets are implemented by [`t_okp_t1fu` in `dft/common/genus.c`](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/common/genus.c#L244-L254) which calls [`t_okp_commonu `](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/dft/simd/common/genus.c#L214-L230), which calls `SIMD_STRIDE_OK` on the strides. Whereas the `t1f.h` codelets use [`t_okp_t1f `](dft_t1fsimd_genus), which calls [`t_okp_common`](7184fc796279cfa70e4ba62519ac2938054584e6), which calls `SIMD_STRIDE_OKA`. These `SIMD_STRIDE_OK` and `SIMD_STRIDE_OKA` checks, in turn, are implemented in [`simd-common.h`](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/simd-support/simd-common.h#L95-L96), and the latter imposes a more stringent alignment check for [some architectures and precisions](https://github.com/FFTW/fftw3/blob/7184fc796279cfa70e4ba62519ac2938054584e6/simd-support/simd-common.h#L26-L63).

I learned a lot about FFTW from your commets. Thanks so much!
