### ISSUE TITLE
libfftw3f.so：对‘log@GLIBC_2.29’未定义的引用

### ISSUE THREAD

**Issue by dfy888** [FFTW/fftw3#266]
libfftw3f.so：对‘log@GLIBC_2.29’未定义的引用

glibc2.29到底谁在用？

**Comment by stevengj** [comment]
FFTW uses the `log` function in the standard C library (e.g. here: https://github.com/FFTW/fftw3/blob/e9c510bf92a4fa848982310d2ecc8c5701aa3f6a/api/mapflags.c#L70) — if you compile FFTW using glibc (the GNU implementation of the standard C library), then you need to link your code with glibc.  If you want to use some other standard C library (e.g. musl) you need to compile FFTW with that.
