### ISSUE TITLE
Need help in building fftw .

### ISSUE THREAD

**Issue by mohit9638iitk** [FFTW/fftw3#273]
I want to overload the MPI_Sendrecv() function of fftw. I have one header file named as "lib.h" and code in file named as "lib.c". 

For simple example (say mpi_3d_fftw3.cpp)
I do command line compilation ;-
1. $ mpicc -c -Wall -Werror -fpic lib.c (this create a executable "lib.o").
2. $mpicc mpi_3d_fftw.cpp lib.o -o fftw_non_block -lfftw3_mpi -lfftw3 -lm

So, basically mpi_3d_fftw.cpp will call fftw_execute and internally it uses MPI_Sendrecv() for communication purpose. By compiling with lib.o executable, fftw uses my version of MPI_Sendrecv().

I want to know how to link my library with fftw so that I do not have to compile with my executable for every code.

Please help me in doing this thing.

**Comment by hominhquan** [comment]
There are two possible solutions AFAIK:

1. Dynamic linking (most often): You can compile your code to a separate `libmy_mpi.so` and use the [LD_PRELOAD](https://www.baeldung.com/linux/ld_preload-trick-what-is) trick.
2. Static linking: the best way IMO is to compile FFTW with `-D MPI_Sendrecv=MPI_Sendrecv_custom` and ensure to have the `MPI_Sendrecv_custom()` symbol in your `libmy_mpi.a`

**Comment by mohit9638iitk** [comment]
Thanks @hominhquan ,it has helped me a lot.
