### ISSUE TITLE
PLANNING PROBLEM misleading

### ISSUE THREAD

**Issue by rogerbinns** [FFTW/fftw3#29]
https://github.com/FFTW/fftw3/blob/master/tools/fftw-wisdom.c#L43

When running fftw-wisdom -v it outputs text like this:
```
PLANNING PROBLEM: cif1024
PLANNING PROBLEM: cib1024
PLANNING PROBLEM: cif2048
PLANNING PROBLEM: cib2048
```

I kept trying to work out what the problem was, and annoyed that it wasn't giving more details on this error message.  It turns out that despite the SHOUTING it is actually not an error, and everything is good.  I suggest changing the text to be far less ambiguous.  For example remove the word 'problem' and make PLANNING be Planning.

**Comment by stevengj** [comment]
I can see how you would see it that way; "problem" has long been FFTW's internal terminology to describe the transformation that the plan is being created for.
