### ISSUE TITLE
bench: speed.c:39: assertion failed: can_do(p)

### ISSUE THREAD

**Issue by zhuohoudeputao** [FFTW/fftw3#299]
I got the error when I ran
```shell
./bench -s ik16:2:1h
```
To my knowledge, it tests the r2r guru interface with instride=2 and outstride=1, but it seems fail to create the plan.

**Comment by stevengj** [comment]
You can't do an in-place transform (`i`) with different input and output strides.  Remove the `i` and it should work.

**Comment by zhuohoudeputao** [comment]
> You can't do an in-place transform (`i`) with different input and output strides. Remove the `i` and it should work.

But where and how the code determine that the input and output strides are not equal? I just found that it can create a proper plan.

**Comment by stevengj** [comment]
> I just found that it can create a proper plan.

How?

**Comment by zhuohoudeputao** [comment]
> > I just found that it can create a proper plan.
> 
> How?
> 
> In particular, the failure you are seeing is precisely because `plan_guru_r2r` returned `NULL` for this problem, because there was no algorithm in FFTW that handled this combination of parameters.
> 
> (Run with `./bench -v3 ik16:2:1h` to see more verbose output, and you can see that it is actually calling the planner [here](https://github.com/FFTW/fftw3/blob/9426cd59106ffddde1f55131c07fa9c562fa2f8e/tests/fftw-bench.c#L196-L214).)

Thanks for your help. I mean "can't", sorry for the wrong typing.

**Comment by zhuohoudeputao** [comment]
And another problem, why
```shell
./bench -s ir16:2:1
```
can do? I mean its input and output strides are also different.
