### ISSUE TITLE
"print-plan.c" causing segmentation fault

### ISSUE THREAD

**Issue by ZitingLiu** [FFTW/fftw3#306]
I believe line 27&44 in print-plan.c should be: "plan *pln = p" instead of "plan *pln = p->pln"
since plan has no attribute called plan

**Comment by stevengj** [comment]
No, the line is correct as is.  The struct does [indeed have a field `pln`](https://github.com/FFTW/fftw3/blob/9426cd59106ffddde1f55131c07fa9c562fa2f8e/api/api.h#L63).  (If we had a bug on this line, don't you think we would have noticed some time in the past 20 years that FFTW was failing to compile?)

If you are getting a crash on that line, you must be passing an invalid plan `p`.  For example, perhaps you are passing `NULL` or a plan you have destroyed.
