### ISSUE TITLE
Compilation Error in QT Project Arm64

### ISSUE THREAD

**Issue by stefanusayudha** [FFTW/fftw3#308]
Device Specification : Macbook Pro M1
OS : ventura 13.1
FFTW Version : 3.3.10
QT Version : Qt Creator 9.0.1
Errors :

```
Undefined symbols for architecture arm64:
  "_fftw_destroy_plan", referenced from:
      fft_analyze(signal) in mainwindow.o
  "_fftw_execute", referenced from:
      fft_analyze(signal) in mainwindow.o
  "_fftw_free", referenced from:
      fft_analyze(signal) in mainwindow.o
  "_fftw_malloc", referenced from:
      fft_analyze(signal) in mainwindow.o
  "_fftw_plan_dft_1d", referenced from:
      fft_analyze(signal) in mainwindow.o
```

is there any configuration that i have to apply?

**Comment by stefanusayudha** [comment]
@matteo-frigo so what is the solution?

**Comment by matteo-frigo** [comment]
I have no idea.  You are compiling who knows what program that is looking for fftw who knows where (or not).  mainwindow.o is not part of the fftw distribution.

**Comment by Baiyuetribe** [comment]
same issue with M2
<img width="821" alt="image" src="https://user-images.githubusercontent.com/43716063/218245630-2ebc7646-b3d7-4855-a422-e23edf6b3c92.png">
