### ISSUE TITLE
IBM POWER 8 arch support

### ISSUE THREAD

**Issue by fcannini** [FFTW/fftw3#36]
Hello!

There has been news that IBM would (help) optimize FFTW3 to their new H/W architecture, how is it going? Would the altivec code for older POWER H/W work in this new architecture ?

TIA,
Fabricio

**Comment by rdolbeau** [comment]
From the 2.06/2.07 specs and <https://gcc.gnu.org/onlinedocs/gcc/PowerPC-AltiVec_002fVSX-Built-in-Functions.html#PowerPC-AltiVec_002fVSX-Built-in-Functions>, I'd say for single-precision the current code _should_ work. For double precision, a new implementation would be needed, since the original AltiVec was SP only.

**Comment by fcannini** [comment]
Hi Romain, thanks for your meaningful answer.

Do you know if Is there any concern for endianness with the current fftw3 code?
In other words, would the current code work in a little-endian Operating System and H/W , as opposed to the former POWER H/W and Operating Systems that were big-endian?

Also, do you have any idea of how hard/long would be to implement this ?

TIA,
Fabricio

**Comment by rdolbeau** [comment]
Regarding endianness - I'm not sure, but probably not a lot of issue since FFTW doesn't mess with bytes (only native float or double). In the AltiVec code, there could be issue with some optimised data movement (using vec_perm). I've never seen a little-endian PPC, so I've no experience.

A straightforward port to DP VSX with no particular tweaking shouldn't be difficult. I don't have PPC64 hardware of either endianness, otherwise I might give it a go (working with Qemu is a bit of a pain, and you can't check speed anyway).

**Comment by fcannini** [comment]
If you feel like having a go at it, you can request access to a POWER8 machine here: http://openpower.ic.unicamp.br/minicloud/

There is also the IBM forum where IBM staff hang around that can help you:
https://www.ibm.com/developerworks/community/forums/html/forum?id=a95a744c-e8fd-4228-a57a-1ae837efe457&ps=25

TIA,
Fabricio

**Comment by rdolbeau** [comment]
Interesting, I didn't know there was a way to access recent PPC64 machine on the web. And apparently, both endianness are available. Now, I only need the time...
... incidentally you can simply try the current FFTW3 on this system in single precision to see if it already works in LE :-)

**Comment by eriklindahl** [comment]
Hi Fabricio,

Just forget about the altivec port. That won't work due to the changed endian (and some direct memory access stuff). However, we have both single and double precision versions working well using the new VSX SIMD instruction set. I'll put them in my repo shortly.

**Comment by rdolbeau** [comment]
Darn, you beat me to it :-) In the meantime I was about to suggest the 'generic' support I added in my fork (using GCC's built-in vector facility, should work on any supported SIMD architecture). Not as efficient as a 'true' port, but that could have been a stopgap solution.

**Comment by fcannini** [comment]
@eriklindahl This is great news! Thanks for writing.

@rdolbeau Do you mean using GCC's flags when compiling?

**Comment by rdolbeau** [comment]
@fcannini No, using the vector extensions from GCC: <https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html>.

**Comment by eriklindahl** [comment]
Alright; have a look at https://github.com/eriklindahl/fftw3 and you'll find it. Send me a mail at erik.lindahl@scilifelab.se if you have problems building from a repo and need a tarball.

Currently, the performance on a single Power8 core running at 4GHz is about 10% slower than an x86 core running at 3.7GHz for my single precision 3D FFTs with sizes in the range of 100^3. I would like to squeeze out a little more performance, but at this point I can't find more optimizations in simd-vsx.h. Anybody who finds any, please drop me a line. However, in the end the whole processor is likely to beat x86: You won't find any 12-core Intel processors still running at 4GHz when all 12 cores are active...

There is a bit of detailed docs in simd-vsx.h too. Basically, gcc-4.9 (best) or xlc-1.0.1 or later (not as fast) work fine. clang from llvm-3.7 is still buggy for VSX code, but might get there in the future.

**Comment by fcannini** [comment]
@eriklindahl Thanks a lot. I'm about to receive a POWER8 machine to test some softwares and will send some feedback on the results.

**Comment by eriklindahl** [comment]
Beware of power-saving modes; the machine we've been using had some issues where it did not increase to the max clock right away. You can check what happens in /proc/cpuinfo.

**Comment by rdolbeau** [comment]
VSX is available in the current trunk.
