### ISSUE TITLE
GPL warning

### ISSUE THREAD

**Issue by keesj** [FFTW/fftw3#362]
This project is by **DESIGN** preventing the use of this library into commercial projects and it is a conscious choice to do this.

 see https://www.fftw.org/faq/section1.html#isfftwfree

We are so lucky that most libraries in the real world are released under permissive (e.g. LGPL) licenses but here this is not the case

I do wonder if this would hold in court but the intent is clear.

https://opensource.stackexchange.com/questions/11204/how-do-you-sell-a-hardware-product-that-uses-the-linux-kernel

The GPL only applies to derivative works of the GPL-covered software. In particular: if you modify the covered software, or if you include the covered software (whether in whole or in part) into another software such as by copying code or by linking a library.

The GPL does not extend to other programs, even if those other programs communicate with the GPL-covered program.

So it is perfectly possible to create proprietary applications that run on the GPL-covered Linux kernel. This is quite common. I was just playing a proprietary game on my Linux-based system. Android smartphones run proprietary Google software. And many cars run a proprietary user interface on top of a Linux kernel.

**Comment by keesj** [comment]
More over.. unless all the contributors wave their rights I think it is probably questionable if the original authors can license this code to a company under a permissive license

**Comment by stevengj** [comment]
I'm not sure what your issue is?  Indeed, the GPL choice for FFTW was intentional.

> unless all the contributors wave their rights I think it is probably questionable if the original authors can license this code to a company under a permissive license

MIT requires a copyright assignment for all substantial contributions to FFTW, precisely to allow such relicensing.

**Comment by keesj** [comment]
Thank you for you feedback and spending the time / responding.  The issue IMHO is that releasing a library in such a way (GPL and not LGPL) tries to enforce software outside of the FFTW to follow certain principles in a way I feel is not fair. Libraries are there to be used not to infect

**Comment by stevengj** [comment]
I don't see how it's not fair — authors have no obligation to write software for companies for no charge.

"Infect" is a bad metaphor IMO.   If you don't like FFTW's license, don't use it — it doesn't enter your software without your consent.

Anyway, there have been reams written about the pros and cons of different open-source licenses; I don't think it's productive to continue to debate here.
