### ISSUE TITLE
Issue/bug with 1D FFT/IFFT along third dimension of 3D matrix when FFTW_MEASURE or FFTW_PATIENT are used (FFTW_ESTIMATE works)

### ISSUE THREAD

**Issue by mlgill** [FFTW/fftw3#39]
I have a reproducible issue with performing a 1D FFT/IFFT along the outer dimension of a 3D matrix when FFTW_MEASURE or FFTW_PATIENT are used. FFTW_ESTIMATE works fine and produces the correct results. Transforms along the other two dimensions (inner and middle) also work fine, regardless  which of the three flags are used.

I have provided sample test code to reproduce the issue in this [repo](https://github.com/mlgill/GSL_vs_FFTW). The transform in question is on line 106 of the fftw_code.c file. 

There is also an IPython notebook which verifies the output data. Please let me know if I can clarify anything or provide more information.

**Comment by rdolbeau** [comment]
I'm not sure the way you use fftw_execute_split_dft() is legit. It is quite sensitive to data placement. The comment in the source file is:
 "/* guru interface: requires care in alignment, r - i, etcetera. */"

In particular, planning & executing on the same arrays in your code seems to work. Separate allocation with a fixed offset between real_* and imag_* (i.e. single allocation, fixed offsets) works as well (but only for forward _or_ backward, you would need 2 plans).

**Comment by stevengj** [comment]
Yes, the split interface assumes that the `re - im` offset does not change between planning and execution.  If you want to apply it to a different pair of arrays, the best way is to do a single `fftw_malloc` for both real and imaginary parts (with the first half being real and the second half being imaginary).

Thanks for looking at this, @rdolbeau

**Comment by stevengj** [comment]
In particular, [the manual states](http://fftw.org/doc/New_002darray-Execute-Functions.html#New_002darray-Execute-Functions) the following requirement:

* For split arrays, the separations between the real and imaginary parts, `ii-ri` and `io-ro`, are the same as they were for the input and output arrays when the plan was created. (This condition is automatically satisfied for interleaved arrays.)

**Comment by mlgill** [comment]
Thank you both for the response. I read the manual thoroughly, but I didn't realize what the statement in question meant. I'll let you know if I have further issues.

**Comment by mlgill** [comment]
As a quick followup, everything is now working correctly, so thank you again. I did have to create a separate IFFT plan for the scenario I'm using to correctly reflect the relative location in memory of real/imaginary data when their position is swapped in the execute command.
