### ISSUE TITLE
Please clarify README for building from git.

### ISSUE THREAD

**Issue by JodiTheTigger** [FFTW/fftw3#42]
The instructions for building from git are ambiguous, resulting in people reproducing #9. 

Please change the wording to something like:

"If you are using the git repository, install ocaml, autoconf,
automake, indent and libtool, and execute the bootstrap.sh script **instead of running configure directly**."

**Comment by x42** [comment]
Even with maintainer-mode  configuration succeeds if `ocamlbuild` is not available but the build fails as described in #9 . Ideally  `--enable-maintainer-mode` would fail if ocaml is not installed.

**Comment by matteo-frigo** [comment]
I have clarified the language in README, closing.
