### ISSUE TITLE
How to use functions provided by fftw3 correctly?

### ISSUE THREAD

**Issue by dazhenseu** [FFTW/fftw3#45]
Hi, 
  I want to use the fftw3 library in C++ project, so I call some functions such as "fftwf_plan_dft_r2c","fftwf_plan_dft_c2r", but why errors like " undefined reference to `fftwf_plan_dft_r2c" occurs?

**Comment by stevengj** [comment]
See [http://fftw.org/faq/section3.html#linkheader](Q3.14 in the FAQ).
