### ISSUE TITLE
relocation R_X86_64_32 against;recompile with -fPIC

### ISSUE THREAD

**Issue by K1two2** [FFTW/fftw3#51]
Kali 2.0 64 / gcc-4.8.2 

/usr/bin/ld: /usr/local/lib/libfftw3f.a(mapflags.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3f.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:396: recipe for target 'libosmodsp.la' failed
make[2]: *** [libosmodsp.la] Error 1
make[2]: Leaving directory '/root/libosmo-dsp/src'
Makefile:475: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/libosmo-dsp'
Makefile:360: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stevengj** [comment]
If you want to compile with `-fPIC`, you would normally just `./configure --enable-shared`
