### ISSUE TITLE
Have you thought about accelerating fftw with OpenCL?

### ISSUE THREAD

**Issue by KOLANICH** [FFTW/fftw3#54]

**Comment by matteo-frigo** [comment]
Wontfix.

**Comment by tallenintegsys** [comment]
Has FFTw been ported to Android yet? If not I'm looking for an NDK project.
I need to learn gradle-experimental and this seems a good thing to do... I
need a goal.

**Comment by SETIguy** [comment]
It 3.3.4 compiles on android with a small fix to the timing routines.  I
was planning on porting that to the current version on github but haven't
had time.  Maybe Matteo or Steven will the equivalent change.
(The difference was that CLOCK_SGI_CYCLE gives 1 second resolution rather
than just being the same as CLOCK_PROCESS_CPUTIME_ID)

https://setisvn.ssl.berkeley.edu/trac/changeset/3318/lib/fftw-3.3.4/kernel/cycle.h
