### ISSUE TITLE
No rule to make target `n1_2.c', needed by `all'. Stop.

### ISSUE THREAD

**Issue by mkschreder** [FFTW/fftw3#56]
Ubuntu. 

v3.3.4 release.

**Comment by matteo-frigo** [comment]
Martin K. Schröder <notifications@github.com> writes:

> Ubuntu. 
>
> v3.3.4 release. 

You are more likely to receive a useful answer if you post a precise
transcript of what you did.  Start by unpacking fftw-3.3.4.tar.gz in a
fresh directory.

**Comment by mkschreder** [comment]
Unpack, ./bootstrap.sh && ./configure && make. Standard build process. I'm
getting the same error even on older versions. So I resorted to using
prebuilt package instead.

**Comment by matteo-frigo** [comment]
Martin K. Schröder <notifications@github.com> writes:

> Unpack, ./bootstrap.sh && ./configure && make. Standard build process.
> I'm
> getting the same error even on older versions. So I resorted to using
> prebuilt package instead.

See README (note the need for --enable-maintainer-mode to generate
the C code):

------------------------------------------------------------
INSTALLATION FROM THE GIT REPOSITORY:

First, install these programs:

  ocaml, ocamlbuild, autoconf, automake, indent, and libtool,

Then, execute

    sh bootstrap.sh
    make
    
The bootstrap.sh script runs configure directly, but if you need to
re-run configure, you must pass the --enable-maintainer-mode flag:

    ./configure --enable-maintainer-mode [OTHER CONFIGURE FLAGS]

**Comment by lvc** [comment]
Why configure doesn't report an error about missed ocaml?

**Comment by stevengj** [comment]
@Ivc, because ocaml isn't needed for people building from the .tar.gz file (where the code has already been generated).  Bootstrapping is mainly intended for experienced developers.

**Comment by MathiasMagnus** [comment]
the codelets from tar.gz. (and zip) from release 3.3.5 and 3.3.4 are missing, so it's not quite true that ocaml is not needed.

**Comment by stevengj** [comment]
@MathiasMagnus, the actual release tarball, e.g. http://fftw.org/fftw-3.3.5.tar.gz, has all of the codelets and does not require ocaml.
