### ISSUE TITLE
Does planning a FFT depend on the actual data content?

### ISSUE THREAD

**Issue by fake-name** [FFTW/fftw3#61]
Basically the title. Does the plan generation for a DFT depend on the actual content of the input array, or just the size and whether the input and output are co-located?

I'm working in a environment where I have many worker threads doing parallel DFTs, and moving the planning out of the threads (*that* was a fun bug to track down) means I don't have ready access to a example instance of the data to pass into the planner. Can I just use a empty array of the same size as the data?

**Comment by zbeekman** [comment]
The plan can be saved and reused so long as the array dimensions are the same, in/out of place transform is the same, array data types are the same (single vs double precision etc)

There's no need for a new plan if only the values of the arrays change.

**Comment by fake-name** [comment]
My point was more "can I create an empty array of the correct size/datatype/in-out-structure, and plan from that?". The documentation is pretty clear you can share plans for what I'd assume is *similar* data, but I don't know if the data content has to be similar, or if it doesn't matter at all.

**Comment by zbeekman** [comment]
I'm pretty confident your approach will work, and that you can plan with dummy data.

**Comment by stevengj** [comment]
You don't need to initialize it.   FFTW automatically overwrites the input with zeros when planning (unless you use `FFTW_ESTIMATE`, which leaves the input array untouched as documented in the manual: http://fftw.org/doc/Complex-DFTs.html#Complex-DFTs).

In particular, FFTW the array to zero [before taking measurements](https://github.com/FFTW/fftw3/blob/d7c566eb98523c7c0bafae734c7894a5a3595771/kernel/timer.c#L149) (which calls a problem-specific code to zero the input, e.g. [here](https://github.com/FFTW/fftw3/blob/d7c566eb98523c7c0bafae734c7894a5a3595771/dft/problem.c#L60-L66) for complex DFTs, which in turn calls [fftw_dft_zerotens](https://github.com/FFTW/fftw3/blob/master/dft/zero.c)).

Timing measurements generally don't depend on the values of the input (a multiplication or addition has the same cost on modern CPUs independent of the values), with one exception: floating-point exceptions (calculations which produce `Inf` or `NaN`) are expensive.   We initialize the arrays to zero for benchmarking to guarantee that performing the transform will not generate fp exceptions.

**Comment by fake-name** [comment]
@stevengj - That was my guess, but thank you for giving me a definitive answer. I didn't see that particular docs page, it basically answers my question.

**Comment by matteo-frigo** [comment]
(Being pedantic here, mostly for amusement value.)
Some "modern" CPU do indeed exist where the timing of floating-point operations is data-dependent.  For example, I have used a not too old machine made by IBM where the normalization unit at the end of the floating-point pipeline could shift by up to 16 bits in one cycle, falling back to a slower path for larger shifts.  Let a=1+2**(-k) and b=1.  On that machine, a-b takes one cycle for k<16 and seven cycles for k>=16, for some value of 16 that I don't quite remember, and for some value of "seven".

There are more things in heaven and earth than we are willing to model in FFTW.

**Comment by fake-name** [comment]
I just wanted to be sure it wasn't doing stats on the input array or something. Sure, it seemed pretty far fetched to me, but then I don't have a great grasp of the underlying code, so I figured I'd best ask.

Thanks!
