### ISSUE TITLE
Please consider doing a release.

### ISSUE THREAD

**Issue by magnetophon** [FFTW/fftw3#64]
I'd like to package a version of fftw3 for my distro with #16 fixed.
There's bound to be many other good reasons to upgrade as well.
Of course I can just pkg a git version, but a curated release would be better.

 Thanks

**Comment by magnetophon** [comment]
Any news on this?

**Comment by matteo-frigo** [comment]
I have tagged fftw-3.3.5-rc1, give me a few days to test the various SIMD options with various compilers and linux/osx/*bsd.

**Comment by magnetophon** [comment]
@matteo-frigo Great! Thanks!

**Comment by x42** [comment]
+1  Thanks for keeping the ball rolling.

**Comment by matteo-frigo** [comment]
Can you guys download 

    http://fftw.org/~athena/fftw-3.3.5-rc1.tar.gz

and give it a try?  (I only have done limited tests so far.)

**Comment by magnetophon** [comment]
@matteo-frigo It can be easily tested [on NixOS](https://github.com/NixOS/nixpkgs/pull/17112).
That uses fftw-3.3.5-rc1.tar.gz from github, which is the same, I assume.

**Comment by matteo-frigo** [comment]
3.3.5 is out, closing

**Comment by magnetophon** [comment]
Thanks!
