### ISSUE TITLE
Compiler error on amd64-cpuid.h

### ISSUE THREAD

**Issue by nrudaz** [FFTW/fftw3#68]
**Error message**
`compilation aborted for avx2.c (code 2)`
`libtool: compile:  /c/port/fftw-3.3.5/fftw-3.3.5/compile icl -no-gcc -DHAVE_CONF IG_H -I. -I.. -I../kernel -O3 -ansi-alias -malign-double -c -showIncludes avx2.c -o avx2.obj`
`avx2.c`
`c:\port\fftw-3.3.5\fftw-3.3.5\simd-support\amd64-cpuid.h(44): error: identifier "op" is undefined`
`      __cpuidex(CPUInfo, op, ecxval);`
`..................^`

**Observations**
. `op` is indeed undefined in the body and signature of the caller function
` cpuid_all(int level, int ecxval, int *eax, int *ebx, int *ecx, int *edx)`
. comparing the semantics of `__cpuidex` and `__cpuid`, it looks like `level` should replace `op`:
  [Source: MSDN | __cpuid, __cpuidex](https://msdn.microsoft.com/en-us/library/hskdteyh.aspx)

**Fix**
replace line 44 of amd64-cpuid.h:
` __cpuidex(CPUInfo, op, ecxval);`
with:
` __cpuidex(CPUInfo, level, ecxval);`

**Test of the fix**
. fftw compiles
. bench compiles and link
. bench runs and outputs expected results

**System details**
. OS: Windows 7 SP1
. FFTW 3.3.5 configured  under MINGW32 with: `./configure --enable-single --enable-avx --enable-openmp CC=icl LD=xilink`
. Compiler: Intel(R) C++ Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 16.0.3.207 Build 20160415
. Development environment: Microsoft Visual Studio Professional 2013

**Comment by stevengj** [comment]
Already fixed by c018cbe430fd6b2af31d594c27a0aaf711292567
