### ISSUE TITLE
FFTW 3.3.5 cross-compile for AArch64 CNTVCT_EL0 checking

### ISSUE THREAD

**Issue by ctan-cktcon** [FFTW/fftw3#73]
Hi,

I am cross-compiling for AArch64 and ran into an issue with configure failing as follows (see config.log.txt as well):

_checking armv8 has 64 bits readable CNTVCT_EL0... configure: error: in `/home/user/Downloads/fftw-3.3.5/test_configure':
configure: error: cannot run test program while cross compiling
See `config.log' for more details_

I looked at the configure file, and found that when cross-compiling, the script is automatically set up to fail when checking for the CNTVCT_EL0 register.  I made a some rudimentary tweaks to the configure file so that by using HAS_CNTVCT_EL0=xxx on the command line (where xxx is any text), CNTVCT_EL0 can be forced (there should also be a method by which it can be disabled instead of failing, but I didn't go that far).  I am including the modified configure file here as configure.txt.

Ideally perhaps, if cross-compiling, the CFLAGS option could be scanned and if a supported processor is found (cortex-a54, cortex-a57, cortex-a72, et. al.) CNTVCT_EL0 could be enabled, otherwise it could be disabled (I don't think it should automatically cause configure to fail).

I am posting this in the hopes it might help others who might be running into this problem.

Best regards,
Chris
[config.log.txt](https://github.com/FFTW/fftw3/files/468601/config.log.txt)
[configure.txt](https://github.com/FFTW/fftw3/files/468604/configure.txt)

**Comment by chewi** [comment]
Agreed, this is very annoying. Checking the flags seems like a decent fallback or at the very least, it should simply assume its unsupported when cross-compiling. If you want to use a variable instead then you should use AC_CACHE_CHECK. See the [autoconf manual](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Caching-Results.html#Caching-Results).

**Comment by matteo-frigo** [comment]
Sorry about this.  We have been disciplined over 20 years in allowing FFTW to be cross-compiled, but this one escaped my attention for some reason.  See 3e7ee2211ae1bd5e76901bbe1bcca67b31f84ccb for a fix.

I am still totally confused about these ARM cycle counters (which were mostly contributed by independent people over the years).  Can somebody familiar with the ARM situation take a look and tell me whether the current code makes sense?  What's the difference between PMCCTR_EL0 and CNTVCT_EL0?

**Comment by chewi** [comment]
Thank you for striving to maintain that policy. I'm afraid I can't comment on the cycle counters.

**Comment by ctan-cktcon** [comment]
Thanks Matteo!  One can't catch everything when there are so many options... 

I wish I could add to your understanding of the ARM registers, but at this point I am not familiar with them either.
