### ISSUE TITLE
Add support for cmake-based builds

### ISSUE THREAD

**Issue by shadowwalkersb** [FFTW/fftw3#75]
We are trying to add a Windows recipe on [conda-forge](http://conda-forge.github.io/) for fftw3, see the discussion [here](https://github.com/conda-forge/fftw-feedstock/issues/2). Would it be possible to work something out if there is a `config.h.in` that we can make CMake use? Or, is there an easier alternative that would be recommended?

**Comment by shadowwalkersb** [comment]
To clarify, we can provide `CMakeLists.txt` that will be part of fftw3 distribution. `config.h.in` could be auto-generated for cmake, or just a separate file. `config.h.in` file would have to have `#cmakedefine` or `#cmakedefine01` (this is where we need help from fftw3 team) instead of `#undef`. I guess, we could hand-craft `config.h.in` and have it and `CMakelIsts.txt` as part of our recipe, but it would be much better if it is part of fftw3 and updated accordingly when things change in fftw3 rather than we track changes and update our recipe manually.

**Comment by matteo-frigo** [comment]
Would you mind being more specific about what exactly you are expecting us to do?  What exactly would we have to do to make config.h.in be of your liking?

**Comment by shadowwalkersb** [comment]
The way I see it there are a couple types of macros. A couple of lines how the current `config.h.in` looks followed by what's desirable for cmake-based builds.

1. **set to 1 if applicable**
    ```
    #undef DISABLE_FORTRAN
    #undef FFTW_LDOUBLE
    ```
    
    ```
    #cmakedefine DISABLE_FORTRAN
    #cmakedefine FFTW_LDOUBLE
    ```
2. **set to a value**
    ```
    #undef SIZEOF_DOUBLE
    #undef PACKAGE_NAME
    #undef PACKAGE_VERSION
    ```

    ```
    #cmakedefine SIZEOF_DOUBLE @SIZEOF_DOUBLE@
    #cmakedefine PACKAGE_NAME @PACKAGE_NAME@
    #cmakedefine PACKAGE_VERSION @PACKAGE_VERSION@
    ```

3. **not sure how to handle**
    ```
    /* Define to `__inline__' or `__inline' if that's what the C compiler
       calls it, or to nothing if 'inline' is not supported under any name.  */
    #ifndef __cplusplus
    #undef inline
    #endif
    
    /* Define to `unsigned int' if <sys/types.h> does not define. */
    #undef size_t
    ```

Does that look reasonable @ukoethe and @jakirkham? Any thoughts on how to handle group 3?

**Comment by xantares** [comment]
Hi, I already started work on this: https://github.com/xantares/fftw-cmake : it builds on linux only, but osx & windows are not really that far, it just needs some macros to generate codelist.c sources.
There's a lot more work involved than just define these few macros though, especially if we want to support building from git sources and not the dist tarball, or support all the cpu instructions.

**Comment by shadowwalkersb** [comment]
The macros I gave in my comment are just examples. All the macros need to be defined, not just the ones listed there. I am just saying to clarify. Thanks @xantares for your work. I will check it out.

**Comment by xantares** [comment]
hey, the build succeeds on windows now, and some basic tests succeed.

**Comment by shadowwalkersb** [comment]
Great! What's next? A PR here?

**Comment by xantares** [comment]
i thinks it's not ready yet, I guess many things are missing.

**Comment by jakirkham** [comment]
Still a PR will make it easier for others to help and advise. What do you think?

**Comment by shadowwalkersb** [comment]
Any chance of getting any updates here?

**Comment by EikeVerdenhalven** [comment]
@shadowwalkersb : You might take a look here #80

**Comment by shadowwalkersb** [comment]
Closing as cmake support has been added long time ago.
