### ISSUE TITLE
FFTW 3.3.5 --enable-avx build failed by using pgcc

### ISSUE THREAD

**Issue by DarthLaran** [FFTW/fftw3#78]
Hello all!

I tried to build FFTW version 3.3.5  with --enable-avx flag by using PGI-16.9 compiler and got the following errors:

PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx.h: 262)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx.h: 271)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx.h: 280)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx.h: 289)

Using --enable-avx2 provides another errors of the same type:
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 102)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 103)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 104)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 105)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 90)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 91)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 94)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 95)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 96)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_10.c: 98)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 100)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 101)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 102)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 106)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 107)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 108)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 83)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 86)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 87)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 88)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 89)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 90)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 91)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 94)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 95)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 96)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_11.c: 97)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_3.c: 54)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_5.c: 64)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_5.c: 65)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_5.c: 68)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_5.c: 70)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_5.c: 71)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_6.c: 69)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_6.c: 71)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 70)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 71)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 72)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 73)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 75)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 76)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 79)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 80)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 81)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 82)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 85)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 86)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 87)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 88)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_7.c: 89)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_8.c: 80)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_8.c: 81)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_8.c: 82)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_8.c: 83)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 103)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 104)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 105)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 106)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 107)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 108)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 110)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 111)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 83)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 87)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 89)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 93)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 94)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 95)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 96)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 97)
PGC-S-0094-Illegal type conversion required (./../common/n1fv_9.c: 98)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 263)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 273)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 278)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 282)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 301)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 341)
PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 349)

Is any way to overcome this issue, except disabling avx and avx2 ?

**Comment by matteo-frigo** [comment]
I don't have pgcc available, but the compiler seems to complain about function FLIP_RI() and the fix is probably a one-line change (except that I don't know what pgcc wants).  It sounds like pgcc gets confused by our way of expressing the shuffle instructions, presumably because the underlying instruction operates on integers and we use it to shuffle floating-point numbers.  Maybe there is some other way to express it, but you will have to dig into this.

**Comment by DarthLaran** [comment]
I hope  you are right that it one-line change fix this problem, but I am not familiar with fftw3 sources to find this line. In particular I don't understand the relationship between FLIP_RI function (line 232 in avx.h) and type conversion problem at  V tr = VDUPL(tx);  (line 262 of the same file).

I also checked the situation with version 3.3.4:
There are no  problems to compile it with --enable-avx by PGI-16.9, but the segmentation prolem from https://github.com/FFTW/fftw3/issues/55 still exist

**Comment by matteo-frigo** [comment]
Try copying FLIP_RI from 3.3.4 and see if it work.

In fact, you can copy the whole file from 3.3.4 and it should work.

**Comment by matteo-frigo** [comment]
Let me know if copying simd-avx.h from 3.3.4 works.  I have preemptively reinstated the old 3.3.4 file in our master repository, since I couldn't measure any performance difference between the 3.3.4 and the 3.3.5 versions, and I assume that 3.3.5 breaks PGI but 3.3.4 doesn't.  So we may as well distribute the 3.3.4 version going forward.  Better still, can you try the latest simd-avx.h from github and let me know if it works?

**Comment by DarthLaran** [comment]
1)Copying  FLIP_RI changes nothing. Compilation still fails
2)Copying  the whole simd-avx.h solve the compilation issue, but we have the same situation with segmentation fault as in https://github.com/FFTW/fftw3/issues/55
3)Copying  the whole simd-avx.h doesn't solve compilation issue with --enable-avx2
All results above were obtained at PGI 16.9

**Comment by DarthLaran** [comment]
The situation with latest simd-avx.h is the same as with one from 3.3.4: compilation is OK, but 
./bench --verbose=1    --verify 'ifc12x24v11' failed with segmentation fault

**Comment by matteo-frigo** [comment]
Alright.  Now you must pester the PGI guys, because my conclusion at the time was that the segfault was a compiler bug.

**Comment by DarthLaran** [comment]
You are right, that is compiler bug and following the google it can be avoid by the using the older version of PGI compiler. But this workaround doesn't solve compiling issue for --enable-avx2, when, 
as for me, the avx2 support is the main reason to make an  upgrade to 3.3.5.

**Comment by matteo-frigo** [comment]
avx2 doesn't make much of a difference.  E.g., on my machine, a 1024-point takes 2.60us with AVX and 2.30US with AVX2, and that's the best case (small problem, in cache, no memory pressure).

Anyway, my guess is that the compiler doesn't like _mm256_permute_pd().  Can you try changing the definition of VPERM1 as follows:

#define VPERM1(x, b) VSHUF((x), (x), b)

If that's not enough, replace the other calls to _mm256_permute_pd(x, b) with _mm256_shuffle_pd(x, x, b)

**Comment by DarthLaran** [comment]
I am not sure that problem is in _mm256_permute_pd.
The first compiler error appears at line 263 of simd-avx2.h  i.e. in function VZMUL:

```
256 static inline V VZMUL(V tx, V sr)
257 {
258      /* V tr = VDUPL(tx); */
259      /* V ti = VDUPH(tx); */
260      /* tr = VMUL(sr, tr); */
261      /* sr = VBYI(sr); */
262      /* return VFMA(ti, sr, tr); */
263      return SUFF(_mm256_fmaddsub_p)(sr, VDUPL(tx), VMUL(FLIP_RI(sr), VDUPH(tx)));
264 }

```
If I remove comments and comment return SUFF:

```
256 static inline V VZMUL(V tx, V sr)
257 {
258       V tr = VDUPL(tx); 
259       V ti = VDUPH(tx); 
260       tr = VMUL(sr, tr); 
261       sr = VBYI(sr); 
262       return VFMA(ti, sr, tr); 
263      //return SUFF(_mm256_fmaddsub_p)(sr, VDUPL(tx), VMUL(FLIP_RI(sr), VDUPH(tx)));
264 }

```
errors appear at lines 258 and 262

> PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 258)
> PGC-S-0094-Illegal type conversion required (../../../simd-support/simd-avx2.h: 262)

i.e. at VDUPL and VFMA:
` 71 #define VDUPL(x) DS(_mm256_movedup_pd(x), _mm256_moveldup_ps(x))`
`247 #define VFMA    SUFF(_mm256_fmadd_p)`

By the way, at what platform you made your comparation with avx2?

**Comment by matteo-frigo** [comment]
DarthLaran <notifications@github.com> writes:

> By the way, at what platform you made your comparation with avx2?

Haswell (Xeon E3v3)
