### ISSUE TITLE
fftw_destroy_plan patch should be backported to fftw-3.3.5.

### ISSUE THREAD

**Issue by NanXiao** [FFTW/fftw3#79]
I think this [patch](https://github.com/FFTW/fftw3/commit/402d2508fe970770d9316d9c83f21d6fc268ba12) should be backported to fftw-3.3.5, otherwise, it is not really thread safe even `fftw_make_planner_thread_safe()` has been called. As this [issue](http://stackoverflow.com/questions/39835403/different-results-when-using-openmp-and-fftw) has mentioned, the core dump will occur during multiple thread call `fftw_destroy_plan()`.

**Comment by matteo-frigo** [comment]
I am not sure what you mean by backport---we can't have two different releases called 3.3.5.
We'll just release 3.3.6 once I get a chance.

**Comment by NanXiao** [comment]
@matteo-frigo what I mean is since it is a critical bug, it should be merged into 3.3.5 release package. If 3.3.6 will be released soon, I think it should be OK. Thx!

**Comment by stevengj** [comment]
Yes, this has to be 3.3.6.   If 3.3.6 isn't ready yet, one option would be to create a new branch from 3.3.5, apply that one patch, and make a 3.3.6 release with just that additional patch.

**Comment by matteo-frigo** [comment]
I have released fftw-3.3.6.  You can obtain it from fftw.org, as usual.  (Do not attempt to rebuild from github unless you know what you are doing.)
