### ISSUE TITLE
FFTW3 3.3.6 shared version rollback

### ISSUE THREAD

**Issue by BSDKaffee** [FFTW/fftw3#82]
In SHARED_VERSION_INFO, REVISION and AGE were bumped causing a rollback of the major library version (calculated as 2 instead of 3). Either CURRENT should have been bumped as well, or AGE should not have been. I would suspect the latter in this case.

**Comment by matteo-frigo** [comment]
Oh darn, now I get it.  libtool does the subtraction and produces libfftw3.so.2.6.6.  Grrr.  I'll make a new release.

**Comment by BSDKaffee** [comment]
Yeah, that's what I meant. I was updating the FreeBSD port and was wondering why the library went to 2.6.6. Thanks for fixing! :)

**Comment by matteo-frigo** [comment]
I'll withdraw 3.3.6 from the website and publish 3.3.6-pl1 soon

**Comment by BSDKaffee** [comment]
Much appreciated!

**Comment by matteo-frigo** [comment]
try again now

**Comment by BSDKaffee** [comment]
Looks good to me. Thanks again!
