### ISSUE TITLE
Offer the same version of FFTW on Github as on the FFTW homepage

### ISSUE THREAD

**Issue by tbole** [FFTW/fftw3#85]
This is not really a bug, however would ease automatic build processes for some projects, to be able to simple get AND BUILD FFTW from Github. Plus it is somewhat confusing to have an official FFTW repo on Github, which does not offer official FFTW releases (yes I have read the warnings).
If it is only the configure scripts. that are missing, you could maybe provide the autoconf script to generate them.

**Comment by stevengj** [comment]
It's not just the `configure` script. To build FFTW from github, you need autoconf, automake, libtool, and ocaml installed.   

It's not generally good practice to include generated code in a version-control repository.

**Comment by tbole** [comment]
Sure, I can understand that you don't want to have autogenerated code in git.
With the configure scripts I actually meant the scripts you are using to generate the official download version. Is it sufficient to just run autoreconf as done in bootstrap?
``autoreconf --verbose --install --symlink --force``

**Comment by matteo-frigo** [comment]
Run mkdist.sh

**Comment by stevengj** [comment]
Probably the repo README should give a list of tools that are required and a pointer to mkdist.sh.

**Comment by tbole** [comment]
Oops, I must have been blind to not see that file, it's really straight forward. I think this issue can closed.
@stevengj Yes it may actually be helpful mentioning mkdist.sh.
