### ISSUE TITLE
Enable compiling with LTO

### ISSUE THREAD

**Issue by CapacitorSet** [FFTW/fftw3#90]
Because FFTW aims to be a high-performance library, it would certainly benefit from being compiled with link-time optimization: [here](https://gcc.gnu.org/onlinedocs/gccint/LTO-Overview.html) is a technical gcc doc about it.

**Comment by matteo-frigo** [comment]
We proactively *disable* optimizations to prevent compilers from screwing up our code.  If you have numbers that prove that LTO is beneficial, please post them.  Meanwhile, WONTFIX.
