### ISSUE TITLE
N must be int32 in fftw_plan_dft_1d(N, in, out, FFTW_FORWARD, FFTW_ESTIMATE)?

### ISSUE THREAD

**Issue by TianyiPeng** [FFTW/fftw3#93]
I am not sure if I am correct. It seems that N must be int32 when we call the function fftw_plan_dft_1d(). This limits the maximal length of the array.

**Comment by stevengj** [comment]
You can use 64-bit sizes (on a 64-bit machine) via the [guru64 interface](http://fftw.org/doc/64_002dbit-Guru-Interface.html#g_t64_002dbit-Guru-Interface).

**Comment by stevengj** [comment]
(When we initially wrote FFTW in late 90s, people expected that `int` would become 64 bits on 64-bit machines, but this ended up not happening.    By the time we realized that we need a 64-bit interface, we didn't want to break binary compatibility, so we did it via a new API function.)

**Comment by TianyiPeng** [comment]
Thanks!
