### ISSUE TITLE
the "plan" issue

### ISSUE THREAD

**Issue by Isco-Chen** [FFTW/fftw3#94]
Hi, I have some doubts about the plan function.
1. If the configure is fixed (e.g. use FFTW_ESTIMATE), do the results of "fftwf_plan_dft_r2c_2d" just depend on the SIZE of the two inputs? That's to say, if we fix the cfg/input sizes, whatever the input data is, the result of this plan will be the same?
2. If 1 is correct, I think we can save the results of plan (p_fft) in advance, and as in my project, the input sizes are fixed, so when I should execute the FFT, the p_fft can be immediately loaded to use and the plan process can be skipped, so that we can speed up the whole FFT time. How do you think?

**Comment by matteo-frigo** [comment]
Isco-Chen <notifications@github.com> writes:

> If the configure is fixed (e.g. use FFTW_ESTIMATE), do the results
> of "fftwf_plan_dft_r2c_2d" just depend on the SIZE of the two inputs?
> That's to say, if we fix the cfg/input sizes, whatever the input data
> is, the result of this plan will be the same?

No.  The plan also depends on the alignments and relative alignments of
IN and OUT.  Generally speaking, plans also depend on array strides, but
for fftwf_plan_dft_r2c_2d the strides are fixed, so this is not a
concern.

> 2 If 1 is correct, I think we can save the results of plan (p_fft) in
> advance, and as in my project, the input sizes are fixed, so when I
> should execute the FFT, the p_fft can be immediately loaded to use and
> the plan process can be skipped, so that we can speed up the whole FFT
> time. How do you think?

See the "wisdom" mechanism documented in the manual.
