### ISSUE TITLE
Documentation for the advanced interface when howmany=0

### ISSUE THREAD

**Issue by pozdneev** [FFTW/fftw3#95]
This is a feature request for the documentation.

Could you please specify in the documentation the behavior of the advanced interface in case of `howmany=0`. Specifically,

- is that a valid value for this argument?
- is that valid for both serial and threaded versions?
- do other arguments matter in this case?

Thanks!

**Comment by stevengj** [comment]
Yes, `howmany=0` is a valid argument for both serial and threaded versions.   FFTW produces an [optimized plan that does nothing](https://github.com/FFTW/fftw3/blob/master/dft/nop.c) in that case :smile:.

The other arguments mostly don't matter in that case, but there are still some sanity checks for valid arguments.  For example, the planner will still checks that the transform dimensions are positive.
